/** Child-friendly word bank for Build a Snowman (A–Z only, common classroom words) */
window.SNOWMAN_WORDS = [
  // K / early
  "CAT","DOG","SUN","MOON","STAR","FISH","BIRD","TREE","BOOK","BALL",
  "FROG","DUCK","BEAR","LION","CAKE","MILK","RAIN","SNOW","WIND","LEAF",
  "HAND","FOOT","NOSE","EYES","HAIR","HOME","DOOR","DESK","PEN","BAG",
  "RED","BLUE","PINK","GREEN","HAPPY","SMILE","JUMP","RUN","PLAY","SING",
  // mid
  "APPLE","TIGER","PENCIL","SCHOOL","FRIEND","TEACHER","GARDEN","FLOWER","RIVER","OCEAN",
  "PLANET","ROCKET","GUITAR","PIZZA","COOKIE","BANANA","ORANGE","PURPLE","YELLOW","WINTER",
  "SUMMER","SPRING","AUTUMN","ISLAND","CASTLE","DRAGON","PIRATE","ROBOT","CIRCUS","PUZZLE",
  "MUSIC","DANCE","STORY","POEM","NUMBER","CIRCLE","SQUARE","TRIANGLE","BRIDGE","TRAIN",
  // stretch
  "ELEPHANT","BUTTERFLY","RAINBOW","SNOWFLAKE","ADVENTURE","KINDNESS","COURAGE","SCIENCE",
  "LIBRARY","COMPUTER","BACKPACK","RECESS","LUNCHBOX","PAINTING","FOOTBALL","BASEBALL",
  "VOLCANO","DINOSAUR","UNICORN","PENGUIN","DOLPHIN","KANGAROO","SANDWICH","CUPCAKE",
  "HOLIDAY","BIRTHDAY","PRESENT","CANDLE","LANTERN","COMPASS","TREASURE","JOURNEY"
];
