/**
 * Comet Clash packs — items may include difficulty: "K" | "1-2" | "3-4" | "all"
 * Engine filters by selected grade band.
 */
window.COMET_PACKS = [
  {
    id: "kinder",
    title: "Kindergarten Stars",
    blurb: "Pictures, colours, simple words — for the youngest crew",
    emoji: "🌟",
    color: "#f9a8d4",
    grades: ["K"],
    items: [
      { q: "Which is a colour?", choices: ["red", "run", "yes", "the"], a: "red", difficulty: "K" },
      { q: "How many legs does a cat usually have?", choices: ["4", "2", "6", "8"], a: "4", difficulty: "K" },
      { q: "What do we drink when we are thirsty?", choices: ["water", "rocks", "paper", "shoes"], a: "water", difficulty: "K" },
      { q: "Which animal says meow?", choices: ["cat", "dog", "cow", "duck"], a: "cat", difficulty: "K" },
      { q: "Which shape is round like a ball?", choices: ["circle", "square", "triangle", "star"], a: "circle", difficulty: "K" },
      { q: "We sleep at…", choices: ["night", "lunch only", "never", "in the pool"], a: "night", difficulty: "K" },
      { q: "Which is a number?", choices: ["3", "go", "big", "happy"], a: "3", difficulty: "K" },
      { q: "What do plants need?", choices: ["sun and water", "only TV", "candy", "shoes"], a: "sun and water", difficulty: "K" },
      { q: "Which one can you eat?", choices: ["apple", "car", "book", "cloud"], a: "apple", difficulty: "K" },
      { q: "Opposite of small:", choices: ["big", "tiny", "quiet", "slow"], a: "big", difficulty: "K" },
      { q: "We use our ears to…", choices: ["hear", "see", "smell", "taste"], a: "hear", difficulty: "K" },
      { q: "Which is the letter A?", choices: ["A", "M", "Z", "S"], a: "A", difficulty: "K" },
      { q: "Dogs like to…", choices: ["bark", "meow", "moo", "quack"], a: "bark", difficulty: "K" },
      { q: "2 + 1 = ?", choices: ["3", "1", "4", "0"], a: "3", difficulty: "K" },
      { q: "The sun is in the…", choices: ["sky", "ocean floor", "backpack", "fridge"], a: "sky", difficulty: "K" },
      { q: "Which is a body part?", choices: ["hand", "chair", "door", "ball"], a: "hand", difficulty: "K" },
    ],
  },
  {
    id: "sight-a",
    title: "Sight Words Blitz",
    blurb: "High-frequency words for early readers",
    emoji: "📖",
    color: "#60a5fa",
    grades: ["K", "1-2"],
    items: [
      { q: "Opposite of stop?", choices: ["go", "sit", "look", "the"], a: "go", difficulty: "K" },
      { q: "A baby cat is a…", choices: ["kitten", "puppy", "cub", "calf"], a: "kitten", difficulty: "1-2" },
      { q: "Which word is a colour?", choices: ["blue", "run", "happy", "under"], a: "blue", difficulty: "K" },
      { q: "I ___ a book yesterday.", choices: ["read", "reads", "reading", "reader"], a: "read", difficulty: "1-2" },
      { q: "Which is a number word?", choices: ["three", "tree", "they", "there"], a: "three", difficulty: "K" },
      { q: "Opposite of big?", choices: ["small", "tall", "fast", "loud"], a: "small", difficulty: "K" },
      { q: "Which can start a sentence about you?", choices: ["I", "am", "is", "the"], a: "I", difficulty: "K" },
      { q: "Pick the animal word:", choices: ["dog", "door", "down", "day"], a: "dog", difficulty: "K" },
      { q: "Which means more than one?", choices: ["cats", "cat", "a cat", "the cat"], a: "cats", difficulty: "1-2" },
      { q: "We ___ to school.", choices: ["go", "goes", "going", "gone"], a: "go", difficulty: "K" },
      { q: "Which is a question word?", choices: ["where", "were", "wear", "ware"], a: "where", difficulty: "1-2" },
      { q: "Find the food word:", choices: ["apple", "April", "open", "after"], a: "apple", difficulty: "K" },
    ],
  },
  {
    id: "phonics",
    title: "Phonics Fuse",
    blurb: "Sounds, blends, and decoding",
    emoji: "🔤",
    color: "#34d399",
    grades: ["K", "1-2", "3-4"],
    items: [
      { q: "Which starts with /sh/?", choices: ["ship", "chip", "sip", "tip"], a: "ship", difficulty: "1-2" },
      { q: "c + h in chair makes…", choices: ["/ch/", "/sh/", "/k/", "/h/"], a: "/ch/", difficulty: "1-2" },
      { q: "Rhymes with cat?", choices: ["hat", "cut", "cot", "kite"], a: "hat", difficulty: "K" },
      { q: "Syllables in elephant?", choices: ["3", "2", "4", "1"], a: "3", difficulty: "3-4" },
      { q: "Long a sound?", choices: ["cake", "cat", "car", "can"], a: "cake", difficulty: "1-2" },
      { q: "Silent e word?", choices: ["bike", "big", "bit", "bin"], a: "bike", difficulty: "1-2" },
      { q: "Blend that starts green?", choices: ["gr", "gl", "cr", "br"], a: "gr", difficulty: "1-2" },
      { q: "Last sound in dog?", choices: ["/g/", "/d/", "/o/", "/t/"], a: "/g/", difficulty: "K" },
      { q: "Ends with /ing/?", choices: ["running", "run", "ran", "runner"], a: "running", difficulty: "1-2" },
      { q: "Which is a digraph?", choices: ["th", "st", "pl", "tr"], a: "th", difficulty: "3-4" },
      { q: "Short i sound?", choices: ["sit", "site", "sight", "side"], a: "sit", difficulty: "1-2" },
      { q: "Rhymes with light?", choices: ["night", "lit", "lot", "net"], a: "night", difficulty: "1-2" },
    ],
  },
  {
    id: "ib-profile",
    title: "IB Learner Profile",
    blurb: "Traits in action — great for PYP",
    emoji: "🌍",
    color: "#a78bfa",
    grades: ["1-2", "3-4"],
    items: [
      { q: "Sharing toys and taking turns is being…", choices: ["Caring", "Risk-taker", "Reflective", "Knowledgeable"], a: "Caring", difficulty: "1-2" },
      { q: "Trying a hard puzzle even when scary — you are a…", choices: ["Risk-taker", "Balanced", "Principled", "Thinker"], a: "Risk-taker", difficulty: "1-2" },
      { q: "Listening to friends from other places — you are…", choices: ["Open-minded", "Communicator", "Inquirer", "Caring"], a: "Open-minded", difficulty: "1-2" },
      { q: "Asking why and digging deeper — you are an…", choices: ["Inquirer", "Thinker", "Balanced", "Principled"], a: "Inquirer", difficulty: "1-2" },
      { q: "Telling the truth when it is hard — you are…", choices: ["Principled", "Caring", "Reflective", "Knowledgeable"], a: "Principled", difficulty: "3-4" },
      { q: "Sport AND reading — body and mind — you are…", choices: ["Balanced", "Risk-taker", "Thinker", "Communicator"], a: "Balanced", difficulty: "1-2" },
      { q: "Explaining an idea clearly — you are a…", choices: ["Communicator", "Inquirer", "Caring", "Reflective"], a: "Communicator", difficulty: "1-2" },
      { q: "Thinking about what went well after a project — you are…", choices: ["Reflective", "Knowledgeable", "Open-minded", "Balanced"], a: "Reflective", difficulty: "3-4" },
      { q: "Using science learning in real life — you are…", choices: ["Knowledgeable", "Risk-taker", "Caring", "Principled"], a: "Knowledgeable", difficulty: "3-4" },
      { q: "Solving a problem in a new way — you are a…", choices: ["Thinker", "Communicator", "Balanced", "Inquirer"], a: "Thinker", difficulty: "3-4" },
      { q: "Fairness and honesty trait?", choices: ["Principled", "Open-minded", "Balanced", "Inquirer"], a: "Principled", difficulty: "3-4" },
      { q: "Empathy and kindness trait?", choices: ["Caring", "Thinker", "Knowledgeable", "Risk-taker"], a: "Caring", difficulty: "1-2" },
    ],
  },
  {
    id: "vocab",
    title: "Word Power",
    blurb: "Classroom vocabulary stretch",
    emoji: "⚡",
    color: "#fbbf24",
    grades: ["1-2", "3-4"],
    items: [
      { q: "Synonym of happy?", choices: ["glad", "angry", "tired", "loud"], a: "glad", difficulty: "1-2" },
      { q: "Antonym of ancient?", choices: ["modern", "old", "dusty", "historic"], a: "modern", difficulty: "3-4" },
      { q: "Enormous means…", choices: ["very big", "very small", "very fast", "very quiet"], a: "very big", difficulty: "1-2" },
      { q: "A person who writes books is an…", choices: ["author", "actor", "artist", "athlete"], a: "author", difficulty: "1-2" },
      { q: "Look carefully means…", choices: ["observe", "ignore", "rush", "hide"], a: "observe", difficulty: "3-4" },
      { q: "Brave is closest to…", choices: ["courageous", "careful", "curious", "calm"], a: "courageous", difficulty: "3-4" },
      { q: "Place to borrow books?", choices: ["library", "cafeteria", "gym", "office"], a: "library", difficulty: "1-2" },
      { q: "Which is a verb?", choices: ["jump", "happy", "blue", "quickly"], a: "jump", difficulty: "1-2" },
      { q: "Which is an adjective?", choices: ["shiny", "run", "slowly", "and"], a: "shiny", difficulty: "1-2" },
      { q: "Beneath means…", choices: ["under", "above", "beside", "inside"], a: "under", difficulty: "1-2" },
      { q: "Plural of child?", choices: ["children", "childs", "childes", "childrens"], a: "children", difficulty: "3-4" },
      { q: "Past tense of go?", choices: ["went", "goed", "goes", "going"], a: "went", difficulty: "1-2" },
    ],
  },
  {
    id: "math",
    title: "Lightning Maths",
    blurb: "Mental maths warm-ups by grade",
    emoji: "🧮",
    color: "#f472b6",
    grades: ["K", "1-2", "3-4"],
    items: [
      { q: "1 + 1 = ?", choices: ["2", "1", "3", "0"], a: "2", difficulty: "K" },
      { q: "3 + 2 = ?", choices: ["5", "4", "6", "1"], a: "5", difficulty: "K" },
      { q: "7 + 8 = ?", choices: ["15", "14", "16", "13"], a: "15", difficulty: "1-2" },
      { q: "12 − 5 = ?", choices: ["7", "6", "8", "17"], a: "7", difficulty: "1-2" },
      { q: "6 × 4 = ?", choices: ["24", "20", "28", "18"], a: "24", difficulty: "3-4" },
      { q: "Half of 10?", choices: ["5", "2", "8", "10"], a: "5", difficulty: "1-2" },
      { q: "Half of 18?", choices: ["9", "8", "10", "6"], a: "9", difficulty: "1-2" },
      { q: "100 − 37?", choices: ["63", "73", "67", "53"], a: "63", difficulty: "3-4" },
      { q: "3 × 9 = ?", choices: ["27", "21", "24", "30"], a: "27", difficulty: "3-4" },
      { q: "Sides on a triangle?", choices: ["3", "4", "5", "6"], a: "3", difficulty: "K" },
      { q: "Sides on a hexagon?", choices: ["6", "5", "8", "7"], a: "6", difficulty: "3-4" },
      { q: "15 ÷ 3 = ?", choices: ["5", "4", "6", "3"], a: "5", difficulty: "3-4" },
      { q: "Which is even?", choices: ["14", "13", "15", "17"], a: "14", difficulty: "1-2" },
      { q: "Double 6?", choices: ["12", "8", "10", "16"], a: "12", difficulty: "1-2" },
      { q: "Double 25?", choices: ["50", "40", "45", "55"], a: "50", difficulty: "3-4" },
    ],
  },
  {
    id: "science",
    title: "Science Spark",
    blurb: "Simple science for curious minds",
    emoji: "🔬",
    color: "#2dd4bf",
    grades: ["K", "1-2", "3-4"],
    items: [
      { q: "Plants need sunlight to make…", choices: ["food", "music", "plastic", "rocks"], a: "food", difficulty: "K" },
      { q: "Frozen water is…", choices: ["ice", "steam", "cloud", "salt"], a: "ice", difficulty: "K" },
      { q: "We live on planet…", choices: ["Earth", "Mars", "Venus", "Jupiter"], a: "Earth", difficulty: "K" },
      { q: "Insects usually have how many legs?", choices: ["6", "4", "8", "2"], a: "6", difficulty: "1-2" },
      { q: "The heart pumps…", choices: ["blood", "only air", "food", "water"], a: "blood", difficulty: "1-2" },
      { q: "What pulls us toward Earth?", choices: ["gravity", "magnetism", "friction", "wind"], a: "gravity", difficulty: "3-4" },
      { q: "Caterpillars can become…", choices: ["butterflies", "frogs", "birds", "fish"], a: "butterflies", difficulty: "K" },
      { q: "Which is a solid?", choices: ["rock", "milk", "air", "steam"], a: "rock", difficulty: "1-2" },
      { q: "Day and night happen because Earth…", choices: ["rotates", "melts", "shrinks", "stops"], a: "rotates", difficulty: "3-4" },
      { q: "We breathe in…", choices: ["oxygen", "only carbon dioxide", "helium", "smoke"], a: "oxygen", difficulty: "1-2" },
      { q: "Magnets attract…", choices: ["iron", "wood", "paper", "plastic"], a: "iron", difficulty: "1-2" },
      { q: "The Moon orbits the…", choices: ["Earth", "Sun only", "Mars", "stars"], a: "Earth", difficulty: "1-2" },
    ],
  },
  {
    id: "boost-pack",
    title: "Boost Pack",
    blurb: "Extra questions across grades — more variety for longer sessions",
    emoji: "🚀",
    color: "#93c5fd",
    grades: ["K", "1-2", "3-4"],
    items: [
      { q: "Which day comes after Monday?", choices: ["Tuesday", "Sunday", "Friday", "Saturday"], a: "Tuesday", difficulty: "K" },
      { q: "What do we use to write?", choices: ["pencil", "shoe", "plate", "ball"], a: "pencil", difficulty: "K" },
      { q: "Which is cold?", choices: ["ice", "fire", "soup", "sun"], a: "ice", difficulty: "K" },
      { q: "A baby cat is called a\u2026", choices: ["kitten", "puppy", "cub", "chick"], a: "kitten", difficulty: "K" },
      { q: "Which one can fly?", choices: ["bird", "fish", "frog", "ant"], a: "bird", difficulty: "K" },
      { q: "We wear a coat when it is\u2026", choices: ["cold", "hot", "always", "never"], a: "cold", difficulty: "K" },
      { q: "How many wheels on a bicycle?", choices: ["2", "3", "4", "1"], a: "2", difficulty: "K" },
      { q: "Which is a fruit?", choices: ["banana", "carrot", "bread", "cheese"], a: "banana", difficulty: "K" },
      { q: "What colour is grass?", choices: ["green", "blue", "purple", "white"], a: "green", difficulty: "K" },
      { q: "Which animal lives in water?", choices: ["fish", "lion", "eagle", "horse"], a: "fish", difficulty: "K" },
      { q: "What do we do with a book?", choices: ["read", "drive", "cook", "kick"], a: "read", difficulty: "K" },
      { q: "Which is soft?", choices: ["pillow", "rock", "metal", "glass"], a: "pillow", difficulty: "K" },
      { q: "What is 5 + 3?", choices: ["8", "7", "9", "6"], a: "8", difficulty: "1-2" },
      { q: "Which word starts with S?", choices: ["sun", "cat", "map", "dog"], a: "sun", difficulty: "1-2" },
      { q: "A triangle has how many sides?", choices: ["3", "4", "5", "2"], a: "3", difficulty: "1-2" },
      { q: "What do bees make?", choices: ["honey", "milk", "bread", "wool"], a: "honey", difficulty: "1-2" },
      { q: "Which is a season?", choices: ["winter", "Monday", "lunch", "school"], a: "winter", difficulty: "1-2" },
      { q: "10 \u2212 4 = ?", choices: ["6", "5", "7", "14"], a: "6", difficulty: "1-2" },
      { q: "Which planet do we live on?", choices: ["Earth", "Mars", "Moon", "Sun"], a: "Earth", difficulty: "1-2" },
      { q: "Opposite of happy:", choices: ["sad", "tall", "fast", "loud"], a: "sad", difficulty: "1-2" },
      { q: "How many months in a year?", choices: ["12", "10", "7", "24"], a: "12", difficulty: "1-2" },
      { q: "Which animal is a mammal?", choices: ["whale", "shark", "goldfish", "octopus"], a: "whale", difficulty: "1-2" },
      { q: "2 + 2 + 2 = ?", choices: ["6", "4", "8", "22"], a: "6", difficulty: "1-2" },
      { q: "Which word means big?", choices: ["huge", "tiny", "quiet", "slow"], a: "huge", difficulty: "1-2" },
      { q: "Half of 10 is\u2026", choices: ["5", "2", "8", "20"], a: "5", difficulty: "1-2" },
      { q: "Which is a vehicle?", choices: ["bus", "tree", "river", "cloud"], a: "bus", difficulty: "1-2" },
      { q: "What is 7 \u00d7 3?", choices: ["21", "24", "10", "14"], a: "21", difficulty: "3-4" },
      { q: "Which is a verb?", choices: ["run", "blue", "table", "happy"], a: "run", difficulty: "3-4" },
      { q: "A square has how many equal sides?", choices: ["4", "3", "5", "6"], a: "4", difficulty: "3-4" },
      { q: "100 \u00f7 4 = ?", choices: ["25", "20", "40", "50"], a: "25", difficulty: "3-4" },
      { q: "Which is a continent?", choices: ["Africa", "Pacific", "Amazon", "Sahara"], a: "Africa", difficulty: "3-4" },
      { q: "Synonym of begin:", choices: ["start", "end", "stop", "finish"], a: "start", difficulty: "3-4" },
      { q: "What is 15% of 100?", choices: ["15", "10", "25", "50"], a: "15", difficulty: "3-4" },
      { q: "Which gas do plants take in?", choices: ["carbon dioxide", "oxygen only", "helium", "nitrogen only"], a: "carbon dioxide", difficulty: "3-4" },
      { q: "A novel is a type of\u2026", choices: ["book", "sport", "tree", "planet"], a: "book", difficulty: "3-4" },
      { q: "Perimeter of a 3\u00d75 rectangle?", choices: ["16", "15", "8", "30"], a: "16", difficulty: "3-4" },
      { q: "Which is a proper noun?", choices: ["London", "city", "river", "teacher"], a: "London", difficulty: "3-4" },
      { q: "3\u00b2 = ?", choices: ["9", "6", "12", "8"], a: "9", difficulty: "3-4" },
      { q: "Water boils at about\u2026", choices: ["100\u00b0C", "0\u00b0C", "50\u00b0C", "10\u00b0C"], a: "100\u00b0C", difficulty: "3-4" },
      { q: "Author of a book is the\u2026", choices: ["writer", "reader only", "page", "cover"], a: "writer", difficulty: "3-4" }
    ],
  },
  {
    id: "mix",
    title: "Cosmic Mix",
    blurb: "A little of everything — filtered by grade",
    emoji: "☄️",
    color: "#fb7185",
    grades: ["K", "1-2", "3-4"],
    items: [],
  },
];

(function () {
  const mix = window.COMET_PACKS.find((p) => p.id === "mix");
  if (!mix) return;
  const pool = [,
  {
    id: "extra-k-boost",
    title: "Kindergarten Boost",
    blurb: "Extra early-years review questions",
    emoji: "🌟",
    color: "#fbbf24",
    grades: ["K", "1-2"],
    items: [
      { q: "Which animal says meow?", choices: ["cat", "dog", "cow", "bird"], a: "cat", difficulty: "K" },
      { q: "5 − 1 = ?", choices: ["4", "6", "3", "1"], a: "4", difficulty: "K" },
      { q: "We write with a…", choices: ["pencil", "plate", "shoe", "window"], a: "pencil", difficulty: "K" },
      { q: "Which is cold?", choices: ["ice", "fire", "sun", "oven"], a: "ice", difficulty: "K" },
      { q: "How many legs does a bird usually have?", choices: ["2", "4", "6", "8"], a: "2", difficulty: "K" },
      { q: "Which shape is round?", choices: ["circle", "square", "triangle", "rectangle"], a: "circle", difficulty: "K" },
      { q: "Opposite of up?", choices: ["down", "left", "fast", "open"], a: "down", difficulty: "K" },
      { q: "We drink…", choices: ["water", "rocks", "paper", "sand"], a: "water", difficulty: "K" },
      { q: "3 + 2 = ?", choices: ["5", "4", "6", "1"], a: "5", difficulty: "K" },
      { q: "Which comes first in the alphabet?", choices: ["A", "M", "Z", "B"], a: "A", difficulty: "K" },
      { q: "A baby dog is a…", choices: ["puppy", "kitten", "cub", "calf"], a: "puppy", difficulty: "K" },
      { q: "Which do we use to see?", choices: ["eyes", "ears", "nose", "feet"], a: "eyes", difficulty: "K" },
    ],
  }
];
  window.COMET_PACKS.forEach((p) => {
    if (p.id === "mix") return;
    p.items.forEach((it) => pool.push({ ...it }));
  });
  mix.items = pool;
})();
