/**
 * Comet Clash packs — items may include difficulty: "K" | "1-2" | "3-4" | "all"
 * Engine filters by selected grade band.
 */
window.COMET_PACKS = [
  {
    id: "kinder",
    title: "Kindergarten Stars",
    blurb: "Pictures, colours, simple words — for the youngest crew",
    emoji: "🌟",
    color: "#f9a8d4",
    grades: ["K"],
    items: [
      { q: "Which is a colour?", choices: ["red", "run", "yes", "the"], a: "red", difficulty: "K" },
      { q: "How many legs does a cat usually have?", choices: ["4", "2", "6", "8"], a: "4", difficulty: "K" },
      { q: "What do we drink when we are thirsty?", choices: ["water", "rocks", "paper", "shoes"], a: "water", difficulty: "K" },
      { q: "Which animal says meow?", choices: ["cat", "dog", "cow", "duck"], a: "cat", difficulty: "K" },
      { q: "Which shape is round like a ball?", choices: ["circle", "square", "triangle", "star"], a: "circle", difficulty: "K" },
      { q: "We sleep at…", choices: ["night", "lunch only", "never", "in the pool"], a: "night", difficulty: "K" },
      { q: "Which is a number?", choices: ["3", "go", "big", "happy"], a: "3", difficulty: "K" },
      { q: "What do plants need?", choices: ["sun and water", "only TV", "candy", "shoes"], a: "sun and water", difficulty: "K" },
      { q: "Which one can you eat?", choices: ["apple", "car", "book", "cloud"], a: "apple", difficulty: "K" },
      { q: "Opposite of small:", choices: ["big", "tiny", "quiet", "slow"], a: "big", difficulty: "K" },
      { q: "We use our ears to…", choices: ["hear", "see", "smell", "taste"], a: "hear", difficulty: "K" },
      { q: "Which is the letter A?", choices: ["A", "M", "Z", "S"], a: "A", difficulty: "K" },
      { q: "Dogs like to…", choices: ["bark", "meow", "moo", "quack"], a: "bark", difficulty: "K" },
      { q: "2 + 1 = ?", choices: ["3", "1", "4", "0"], a: "3", difficulty: "K" },
      { q: "The sun is in the…", choices: ["sky", "ocean floor", "backpack", "fridge"], a: "sky", difficulty: "K" },
      { q: "Which is a body part?", choices: ["hand", "chair", "door", "ball"], a: "hand", difficulty: "K" },
    ],
  },
  {
    id: "sight-a",
    title: "Sight Words Blitz",
    blurb: "High-frequency words for early readers",
    emoji: "📖",
    color: "#60a5fa",
    grades: ["K", "1-2"],
    items: [
      { q: "Opposite of stop?", choices: ["go", "sit", "look", "the"], a: "go", difficulty: "K" },
      { q: "A baby cat is a…", choices: ["kitten", "puppy", "cub", "calf"], a: "kitten", difficulty: "1-2" },
      { q: "Which word is a colour?", choices: ["blue", "run", "happy", "under"], a: "blue", difficulty: "K" },
      { q: "I ___ a book yesterday.", choices: ["read", "reads", "reading", "reader"], a: "read", difficulty: "1-2" },
      { q: "Which is a number word?", choices: ["three", "tree", "they", "there"], a: "three", difficulty: "K" },
      { q: "Opposite of big?", choices: ["small", "tall", "fast", "loud"], a: "small", difficulty: "K" },
      { q: "Which can start a sentence about you?", choices: ["I", "am", "is", "the"], a: "I", difficulty: "K" },
      { q: "Pick the animal word:", choices: ["dog", "door", "down", "day"], a: "dog", difficulty: "K" },
      { q: "Which means more than one?", choices: ["cats", "cat", "a cat", "the cat"], a: "cats", difficulty: "1-2" },
      { q: "We ___ to school.", choices: ["go", "goes", "going", "gone"], a: "go", difficulty: "K" },
      { q: "Which is a question word?", choices: ["where", "were", "wear", "ware"], a: "where", difficulty: "1-2" },
      { q: "Find the food word:", choices: ["apple", "April", "open", "after"], a: "apple", difficulty: "K" },
    ],
  },
  {
    id: "phonics",
    title: "Phonics Fuse",
    blurb: "Sounds, blends, and decoding",
    emoji: "🔤",
    color: "#34d399",
    grades: ["K", "1-2", "3-4"],
    items: [
      { q: "Which starts with /sh/?", choices: ["ship", "chip", "sip", "tip"], a: "ship", difficulty: "1-2" },
      { q: "c + h in chair makes…", choices: ["/ch/", "/sh/", "/k/", "/h/"], a: "/ch/", difficulty: "1-2" },
      { q: "Rhymes with cat?", choices: ["hat", "cut", "cot", "kite"], a: "hat", difficulty: "K" },
      { q: "Syllables in elephant?", choices: ["3", "2", "4", "1"], a: "3", difficulty: "3-4" },
      { q: "Long a sound?", choices: ["cake", "cat", "car", "can"], a: "cake", difficulty: "1-2" },
      { q: "Silent e word?", choices: ["bike", "big", "bit", "bin"], a: "bike", difficulty: "1-2" },
      { q: "Blend that starts green?", choices: ["gr", "gl", "cr", "br"], a: "gr", difficulty: "1-2" },
      { q: "Last sound in dog?", choices: ["/g/", "/d/", "/o/", "/t/"], a: "/g/", difficulty: "K" },
      { q: "Ends with /ing/?", choices: ["running", "run", "ran", "runner"], a: "running", difficulty: "1-2" },
      { q: "Which is a digraph?", choices: ["th", "st", "pl", "tr"], a: "th", difficulty: "3-4" },
      { q: "Short i sound?", choices: ["sit", "site", "sight", "side"], a: "sit", difficulty: "1-2" },
      { q: "Rhymes with light?", choices: ["night", "lit", "lot", "net"], a: "night", difficulty: "1-2" },
    ],
  },
  {
    id: "ib-profile",
    title: "IB Learner Profile",
    blurb: "Traits in action — great for PYP",
    emoji: "🌍",
    color: "#a78bfa",
    grades: ["1-2", "3-4"],
    items: [
      { q: "Sharing toys and taking turns is being…", choices: ["Caring", "Risk-taker", "Reflective", "Knowledgeable"], a: "Caring", difficulty: "1-2" },
      { q: "Trying a hard puzzle even when scary — you are a…", choices: ["Risk-taker", "Balanced", "Principled", "Thinker"], a: "Risk-taker", difficulty: "1-2" },
      { q: "Listening to friends from other places — you are…", choices: ["Open-minded", "Communicator", "Inquirer", "Caring"], a: "Open-minded", difficulty: "1-2" },
      { q: "Asking why and digging deeper — you are an…", choices: ["Inquirer", "Thinker", "Balanced", "Principled"], a: "Inquirer", difficulty: "1-2" },
      { q: "Telling the truth when it is hard — you are…", choices: ["Principled", "Caring", "Reflective", "Knowledgeable"], a: "Principled", difficulty: "3-4" },
      { q: "Sport AND reading — body and mind — you are…", choices: ["Balanced", "Risk-taker", "Thinker", "Communicator"], a: "Balanced", difficulty: "1-2" },
      { q: "Explaining an idea clearly — you are a…", choices: ["Communicator", "Inquirer", "Caring", "Reflective"], a: "Communicator", difficulty: "1-2" },
      { q: "Thinking about what went well after a project — you are…", choices: ["Reflective", "Knowledgeable", "Open-minded", "Balanced"], a: "Reflective", difficulty: "3-4" },
      { q: "Using science learning in real life — you are…", choices: ["Knowledgeable", "Risk-taker", "Caring", "Principled"], a: "Knowledgeable", difficulty: "3-4" },
      { q: "Solving a problem in a new way — you are a…", choices: ["Thinker", "Communicator", "Balanced", "Inquirer"], a: "Thinker", difficulty: "3-4" },
      { q: "Fairness and honesty trait?", choices: ["Principled", "Open-minded", "Balanced", "Inquirer"], a: "Principled", difficulty: "3-4" },
      { q: "Empathy and kindness trait?", choices: ["Caring", "Thinker", "Knowledgeable", "Risk-taker"], a: "Caring", difficulty: "1-2" },
    ],
  },
  {
    id: "vocab",
    title: "Word Power",
    blurb: "Classroom vocabulary stretch",
    emoji: "⚡",
    color: "#fbbf24",
    grades: ["1-2", "3-4"],
    items: [
      { q: "Synonym of happy?", choices: ["glad", "angry", "tired", "loud"], a: "glad", difficulty: "1-2" },
      { q: "Antonym of ancient?", choices: ["modern", "old", "dusty", "historic"], a: "modern", difficulty: "3-4" },
      { q: "Enormous means…", choices: ["very big", "very small", "very fast", "very quiet"], a: "very big", difficulty: "1-2" },
      { q: "A person who writes books is an…", choices: ["author", "actor", "artist", "athlete"], a: "author", difficulty: "1-2" },
      { q: "Look carefully means…", choices: ["observe", "ignore", "rush", "hide"], a: "observe", difficulty: "3-4" },
      { q: "Brave is closest to…", choices: ["courageous", "careful", "curious", "calm"], a: "courageous", difficulty: "3-4" },
      { q: "Place to borrow books?", choices: ["library", "cafeteria", "gym", "office"], a: "library", difficulty: "1-2" },
      { q: "Which is a verb?", choices: ["jump", "happy", "blue", "quickly"], a: "jump", difficulty: "1-2" },
      { q: "Which is an adjective?", choices: ["shiny", "run", "slowly", "and"], a: "shiny", difficulty: "1-2" },
      { q: "Beneath means…", choices: ["under", "above", "beside", "inside"], a: "under", difficulty: "1-2" },
      { q: "Plural of child?", choices: ["children", "childs", "childes", "childrens"], a: "children", difficulty: "3-4" },
      { q: "Past tense of go?", choices: ["went", "goed", "goes", "going"], a: "went", difficulty: "1-2" },
    ],
  },
  {
    id: "math",
    title: "Lightning Maths",
    blurb: "Mental maths warm-ups by grade",
    emoji: "🧮",
    color: "#f472b6",
    grades: ["K", "1-2", "3-4"],
    items: [
      { q: "1 + 1 = ?", choices: ["2", "1", "3", "0"], a: "2", difficulty: "K" },
      { q: "3 + 2 = ?", choices: ["5", "4", "6", "1"], a: "5", difficulty: "K" },
      { q: "7 + 8 = ?", choices: ["15", "14", "16", "13"], a: "15", difficulty: "1-2" },
      { q: "12 − 5 = ?", choices: ["7", "6", "8", "17"], a: "7", difficulty: "1-2" },
      { q: "6 × 4 = ?", choices: ["24", "20", "28", "18"], a: "24", difficulty: "3-4" },
      { q: "Half of 10?", choices: ["5", "2", "8", "10"], a: "5", difficulty: "1-2" },
      { q: "Half of 18?", choices: ["9", "8", "10", "6"], a: "9", difficulty: "1-2" },
      { q: "100 − 37?", choices: ["63", "73", "67", "53"], a: "63", difficulty: "3-4" },
      { q: "3 × 9 = ?", choices: ["27", "21", "24", "30"], a: "27", difficulty: "3-4" },
      { q: "Sides on a triangle?", choices: ["3", "4", "5", "6"], a: "3", difficulty: "K" },
      { q: "Sides on a hexagon?", choices: ["6", "5", "8", "7"], a: "6", difficulty: "3-4" },
      { q: "15 ÷ 3 = ?", choices: ["5", "4", "6", "3"], a: "5", difficulty: "3-4" },
      { q: "Which is even?", choices: ["14", "13", "15", "17"], a: "14", difficulty: "1-2" },
      { q: "Double 6?", choices: ["12", "8", "10", "16"], a: "12", difficulty: "1-2" },
      { q: "Double 25?", choices: ["50", "40", "45", "55"], a: "50", difficulty: "3-4" },
    ],
  },
  {
    id: "science",
    title: "Science Spark",
    blurb: "Simple science for curious minds",
    emoji: "🔬",
    color: "#2dd4bf",
    grades: ["K", "1-2", "3-4"],
    items: [
      { q: "Plants need sunlight to make…", choices: ["food", "music", "plastic", "rocks"], a: "food", difficulty: "K" },
      { q: "Frozen water is…", choices: ["ice", "steam", "cloud", "salt"], a: "ice", difficulty: "K" },
      { q: "We live on planet…", choices: ["Earth", "Mars", "Venus", "Jupiter"], a: "Earth", difficulty: "K" },
      { q: "Insects usually have how many legs?", choices: ["6", "4", "8", "2"], a: "6", difficulty: "1-2" },
      { q: "The heart pumps…", choices: ["blood", "only air", "food", "water"], a: "blood", difficulty: "1-2" },
      { q: "What pulls us toward Earth?", choices: ["gravity", "magnetism", "friction", "wind"], a: "gravity", difficulty: "3-4" },
      { q: "Caterpillars can become…", choices: ["butterflies", "frogs", "birds", "fish"], a: "butterflies", difficulty: "K" },
      { q: "Which is a solid?", choices: ["rock", "milk", "air", "steam"], a: "rock", difficulty: "1-2" },
      { q: "Day and night happen because Earth…", choices: ["rotates", "melts", "shrinks", "stops"], a: "rotates", difficulty: "3-4" },
      { q: "We breathe in…", choices: ["oxygen", "only carbon dioxide", "helium", "smoke"], a: "oxygen", difficulty: "1-2" },
      { q: "Magnets attract…", choices: ["iron", "wood", "paper", "plastic"], a: "iron", difficulty: "1-2" },
      { q: "The Moon orbits the…", choices: ["Earth", "Sun only", "Mars", "stars"], a: "Earth", difficulty: "1-2" },
    ],
  },
  {
    id: "mix",
    title: "Cosmic Mix",
    blurb: "A little of everything — filtered by grade",
    emoji: "☄️",
    color: "#fb7185",
    grades: ["K", "1-2", "3-4"],
    items: [],
  },
];

(function () {
  const mix = window.COMET_PACKS.find((p) => p.id === "mix");
  if (!mix) return;
  const pool = [];
  window.COMET_PACKS.forEach((p) => {
    if (p.id === "mix") return;
    p.items.forEach((it) => pool.push({ ...it }));
  });
  mix.items = pool;
})();
