/**
 * I Spy Spelling — scene packs
 * Images: Twemoji (Twitter Emoji) CC-BY 4.0 — local copies in assets/twemoji/
 * https://github.com/twitter/twemoji
 */
window.ISPY_PACKS = [
  {
    id: "garden",
    title: "Sunny Garden",
    theme: "theme-garden",
    decor: [
      { img: "sunplain", x: 88, y: 12, size: 52 },
      { img: "cloud", x: 20, y: 14, size: 44 },
      { img: "cloud", x: 55, y: 10, size: 36 },
      { img: "tree2", x: 10, y: 48, size: 64 },
      { img: "tree2", x: 90, y: 52, size: 56 },
    ],
    items: [
      { word: "bee", img: "bee", x: 30, y: 35, color: "yellow",
        riddle: "a tiny buzz that visits flowers",
        challenge: "I wear stripes and hum near petals — who am I?" },
      { word: "sun", img: "sun", x: 75, y: 22, color: "yellow",
        riddle: "bright in the sky by day",
        challenge: "I rise in the morning and paint the garden gold — what am I?" },
      { word: "tree", img: "tree", x: 18, y: 62, color: "green",
        riddle: "tall and leafy with a trunk",
        challenge: "I have a trunk but never travel — what am I?" },
      { word: "frog", img: "frog", x: 62, y: 72, color: "green",
        riddle: "hops near the pond",
        challenge: "I hop and ribbit by the water’s edge — who am I?" },
      { word: "rose", img: "rose", x: 48, y: 58, color: "red",
        riddle: "a red flower with soft petals",
        challenge: "Red petals and a sweet garden scent — what flower am I?" },
      { word: "ant", img: "ant", x: 80, y: 78, color: "black",
        riddle: "a tiny crawler on the path",
        challenge: "Tiny, strong, and marching in a line — who am I?" },
    ],
  },
  {
    id: "beach",
    title: "Sandy Beach",
    theme: "theme-beach",
    decor: [
      { img: "wave", x: 50, y: 38, size: 48 },
      { img: "cloud", x: 25, y: 12, size: 40 },
      { img: "cloud", x: 70, y: 16, size: 34 },
    ],
    items: [
      { word: "crab", img: "crab", x: 28, y: 70, color: "red",
        riddle: "sideways walker with claws",
        challenge: "I scuttle sideways and pinch with claws — who am I?" },
      { word: "fish", img: "fish", x: 70, y: 42, color: "orange",
        riddle: "swims under the waves",
        challenge: "I breathe underwater and flick a fin — who am I?" },
      { word: "ball", img: "ball", x: 55, y: 68, color: "white",
        riddle: "round and ready for a beach game",
        challenge: "Round, bouncy, and fun in the sand — what am I?" },
      { word: "shell", img: "shell", x: 40, y: 80, color: "pink",
        riddle: "you might hear the sea inside",
        challenge: "Hold me to your ear — the ocean whispers. What am I?" },
      { word: "boat", img: "boat", x: 82, y: 48, color: "white",
        riddle: "sails on the water",
        challenge: "I float with a sail and ride the waves — what am I?" },
      { word: "star", img: "star", x: 18, y: 55, color: "yellow",
        riddle: "a shiny shape washed ashore",
        challenge: "Five points shine on the shore — what am I?" },
    ],
  },
  {
    id: "classroom",
    title: "Classroom Corner",
    theme: "theme-classroom",
    decor: [
      { img: "window", x: 85, y: 28, size: 44 },
    ],
    items: [
      { word: "book", img: "book", x: 32, y: 72, color: "blue",
        riddle: "full of pages to read",
        challenge: "I open to stories and close with a tale — what am I?" },
      { word: "pen", img: "pen", x: 55, y: 68, color: "blue",
        riddle: "writes with ink",
        challenge: "I leave ink lines when you write — what am I?" },
      { word: "apple", img: "apple", x: 70, y: 60, color: "red",
        riddle: "a teacher’s classic snack",
        challenge: "Crisp, red, and a classroom classic snack — what am I?" },
      { word: "clock", img: "clock", x: 22, y: 28, color: "white",
        riddle: "tells you the time",
        challenge: "I have hands but never clap — what am I?" },
      { word: "glue", img: "glue", x: 45, y: 78, color: "white",
        riddle: "sticks paper together",
        challenge: "I make paper stick for art and crafts — what am I?" },
      { word: "map", img: "map", x: 78, y: 75, color: "green",
        riddle: "shows countries and places",
        challenge: "I show the world without leaving the room — what am I?" },
    ],
  },
  {
    id: "space",
    title: "Starry Space",
    theme: "theme-space",
    decor: [],
    items: [
      { word: "moon", img: "moon", x: 72, y: 28, color: "white",
        riddle: "glows at night in the sky",
        challenge: "I light the night but am not a lamp — what am I?" },
      { word: "star", img: "star", x: 30, y: 22, color: "yellow",
        riddle: "twinkles far away",
        challenge: "I twinkle high above the dark — what am I?" },
      { word: "rocket", img: "rocket", x: 48, y: 55, color: "red",
        riddle: "blasts off toward the stars",
        challenge: "I blast off with a fiery trail — what am I?" },
      { word: "alien", img: "alien", x: 65, y: 70, color: "green",
        riddle: "a friendly visitor from far away",
        challenge: "A friendly visitor from another world — who am I?" },
      { word: "comet", img: "comet", x: 22, y: 48, color: "white",
        riddle: "streaks across space with a tail",
        challenge: "I streak through space with a glowing tail — what am I?" },
      { word: "planet", img: "planet", x: 80, y: 55, color: "yellow",
        riddle: "a world with a bright ring",
        challenge: "A world with rings that spins in space — what am I?" },
    ],
  },
];

window.ISPY_IMG_BASE = "assets/twemoji/";
