/**
 * Word Builder Factory — validated word database
 * Every entry has a real word + emoji cue. No random letter soup.
 */
window.WBF_LEVELS = [
  {
    id: "cvc",
    name: "Level 1 · CVC",
    blurb: "Consonant · Vowel · Consonant",
    highlight: null,
    words: [
      { word: "cat", emoji: "🐱" },
      { word: "dog", emoji: "🐶" },
      { word: "sun", emoji: "☀️" },
      { word: "pig", emoji: "🐷" },
      { word: "hat", emoji: "🎩" },
      { word: "bus", emoji: "🚌" },
      { word: "cup", emoji: "☕" },
      { word: "bed", emoji: "🛏️" },
      { word: "pen", emoji: "🖊️" },
      { word: "map", emoji: "🗺️" },
      { word: "fox", emoji: "🦊" },
      { word: "jam", emoji: "🫙" },
      { word: "net", emoji: "🥅" },
      { word: "log", emoji: "🪵" },
      { word: "run", emoji: "🏃" },
      { word: "sit", emoji: "🪑" },
    ],
  },
  {
    id: "ccvc",
    name: "Level 2 · CCVC",
    blurb: "Blend at the start",
    highlight: "blend",
    words: [
      { word: "frog", emoji: "🐸" },
      { word: "stop", emoji: "🛑" },
      { word: "flag", emoji: "🚩" },
      { word: "crab", emoji: "🦀" },
      { word: "drum", emoji: "🥁" },
      { word: "sled", emoji: "🛷" },
      { word: "swim", emoji: "🏊" },
      { word: "clap", emoji: "👏" },
      { word: "plan", emoji: "📋" },
      { word: "trip", emoji: "🧳" },
      { word: "grab", emoji: "✊" },
      { word: "spin", emoji: "🌀" },
    ],
  },
  {
    id: "cvcc",
    name: "Level 3 · CVCC",
    blurb: "Blend at the end",
    highlight: "end",
    words: [
      { word: "fish", emoji: "🐟" },
      { word: "milk", emoji: "🥛" },
      { word: "hand", emoji: "✋" },
      { word: "jump", emoji: "🦘" },
      { word: "lamp", emoji: "💡" },
      { word: "nest", emoji: "🪺" },
      { word: "desk", emoji: "🖥️" },
      { word: "gift", emoji: "🎁" },
      { word: "mask", emoji: "🎭" },
      { word: "tent", emoji: "⛺" },
      { word: "duck", emoji: "🦆" },
      { word: "belt", emoji: "👔" },
    ],
  },
  {
    id: "digraph",
    name: "Level 4 · Digraphs",
    blurb: "SH · CH · TH · WH",
    highlight: "digraph",
    words: [
      { word: "ship", emoji: "🚢" },
      { word: "chop", emoji: "🪓" },
      { word: "thin", emoji: "📏" },
      { word: "fish", emoji: "🐠" },
      { word: "chat", emoji: "💬" },
      { word: "path", emoji: "🛤️" },
      { word: "when", emoji: "⏰" },
      { word: "shop", emoji: "🏪" },
      { word: "chin", emoji: "😊" },
      { word: "bath", emoji: "🛁" },
      { word: "whip", emoji: "🌀" },
      { word: "shell", emoji: "🐚" },
    ],
  },
  {
    id: "blends",
    name: "Level 5 · Blends",
    blurb: "More starting blends",
    highlight: "blend",
    words: [
      { word: "blue", emoji: "🔵" },
      { word: "frog", emoji: "🐸" },
      { word: "stop", emoji: "🛑" },
      { word: "tree", emoji: "🌳" },
      { word: "star", emoji: "⭐" },
      { word: "plum", emoji: "🟣" },
      { word: "grin", emoji: "😁" },
      { word: "snap", emoji: "🫰" },
      { word: "drop", emoji: "💧" },
      { word: "club", emoji: "♣️" },
      { word: "twin", emoji: "👯" },
      { word: "glad", emoji: "😄" },
    ],
  },
  {
    id: "silent-e",
    name: "Level 6 · Silent e",
    blurb: "Magic e makes the vowel say its name",
    highlight: "silent-e",
    words: [
      { word: "cake", emoji: "🍰" },
      { word: "bike", emoji: "🚲" },
      { word: "home", emoji: "🏠" },
      { word: "cute", emoji: "🥰" },
      { word: "gate", emoji: "🚪" },
      { word: "rope", emoji: "🪢" },
      { word: "mule", emoji: "🫏" },
      { word: "bone", emoji: "🦴" },
      { word: "kite", emoji: "🪁" },
      { word: "hope", emoji: "🙏" },
      { word: "tube", emoji: "🧪" },
      { word: "name", emoji: "🏷️" },
    ],
  },
];
