/** Speaking Spinner — built-in prompt banks by category + difficulty */
window.SPINNER_PROMPTS = {
  animals: {
    label: "Animals",
    color: "#f59e0b",
    easy: [
      "What is your favourite animal?",
      "Can you name three animals?",
      "What sound does a cat make?",
      "Do you like dogs or cats?",
      "What colour is a frog?",
      "Name an animal that can fly.",
      "Name an animal that lives in water.",
      "What does a cow say?",
    ],
    medium: [
      "Describe a lion. What does it look like?",
      "Where does a fish live?",
      "What do rabbits like to eat?",
      "Would you rather be a bird or a fish? Why?",
      "Tell me about an animal at the zoo.",
      "What animal is big and grey?",
      "How does a snake move?",
      "Name two farm animals and one wild animal.",
    ],
    hard: [
      "Explain why animals need food and water.",
      "Compare a cat and a dog. How are they different?",
      "If you could invent a new animal, what would it be?",
      "Why do some animals sleep in winter?",
      "Describe how a bird builds a nest.",
      "What would happen if there were no bees?",
    ],
  },
  personal: {
    label: "Personal",
    color: "#22c55e",
    easy: [
      "What is your name?",
      "How old are you?",
      "What colour do you like?",
      "Do you have a brother or sister?",
      "What is your favourite food?",
      "What makes you happy?",
      "What is your favourite toy?",
      "Who is in your family?",
    ],
    medium: [
      "What did you do yesterday?",
      "What do you like to do after school?",
      "Tell us about your best friend.",
      "What is your favourite subject? Why?",
      "Describe your bedroom.",
      "What makes you laugh?",
      "What are you good at?",
    ],
    hard: [
      "What is a goal you want to achieve?",
      "Describe a time you helped someone.",
      "What would you change about your day?",
      "Explain why friendship is important.",
      "Talk about a challenge you overcame.",
    ],
  },
  story: {
    label: "Story",
    color: "#3b82f6",
    easy: [
      "Once upon a time… continue the story!",
      "What happened next?",
      "Who is the hero of your story?",
      "Name a place in a fairy tale.",
      "Is the ending happy or sad?",
      "What is the magic object?",
    ],
    medium: [
      "Create a story with a dragon and a child.",
      "What problem does the character have?",
      "How does the character solve the problem?",
      "Describe the beginning, middle, and end.",
      "Add a surprising twist to the story.",
      "What does the villain want?",
    ],
    hard: [
      "Retell a familiar story in your own words.",
      "Change the ending of a famous story.",
      "Tell a story from the villain’s point of view.",
      "Invent a story that teaches a lesson.",
    ],
  },
  vocabulary: {
    label: "Vocabulary",
    color: "#ef4444",
    easy: [
      "Name five things you can see in this room.",
      "What is the opposite of hot?",
      "Name three colours.",
      "What do you wear on your feet?",
      "Name something you eat for breakfast.",
      "Point to something round and name it.",
    ],
    medium: [
      "Name three things that are soft.",
      "What is a synonym for happy?",
      "Use the word ‘because’ in a sentence.",
      "Name things that belong in a kitchen.",
      "What is the difference between big and huge?",
      "List words that start with the letter S.",
    ],
    hard: [
      "Explain the word ‘brave’ with an example.",
      "Use ‘although’ in a full sentence.",
      "Give three words that mean almost the same as ‘said’.",
      "Describe the word ‘journey’ without using travel.",
    ],
  },
  describe: {
    label: "Describe",
    color: "#a855f7",
    easy: [
      "Describe an apple. What colour is it?",
      "Describe your school bag.",
      "What does rain feel like?",
      "Describe a sunny day.",
      "Tell me about your shoes.",
    ],
    medium: [
      "Describe a lion using three adjectives.",
      "Describe your favourite place.",
      "How does chocolate taste?",
      "Describe a friend without saying their name.",
      "What does a busy classroom look like?",
    ],
    hard: [
      "Describe a painting as if I cannot see it.",
      "Compare the ocean and a swimming pool.",
      "Describe a feeling using a colour and a weather word.",
    ],
  },
  sentences: {
    label: "Sentences",
    color: "#14b8a6",
    easy: [
      "Make a sentence with the word ‘cat’.",
      "Say a sentence about school.",
      "Make a sentence using ‘I like’.",
      "Finish: I can…",
      "Finish: Today I…",
    ],
    medium: [
      "Make a sentence using ‘because’.",
      "Make a sentence with ‘and’ connecting two ideas.",
      "Ask a question using ‘where’.",
      "Make a sentence in the past tense.",
      "Use ‘want to’ in a sentence.",
    ],
    hard: [
      "Make a complex sentence with ‘although’.",
      "Build a sentence with three adjectives.",
      "Make a question and then answer it.",
      "Use ‘if’ to talk about a possibility.",
    ],
  },
  reasoning: {
    label: "Reasoning",
    color: "#eab308",
    easy: [
      "Why do we wear coats in winter?",
      "Why do we wash our hands?",
      "Why do plants need water?",
      "Why should we share?",
    ],
    medium: [
      "Why is it important to listen in class?",
      "What would happen if it never rained?",
      "Why do we need sleep?",
      "Why should we recycle?",
    ],
    hard: [
      "Why might two people disagree? Give an example.",
      "Explain how teamwork helps solve problems.",
      "What could we do to make our classroom kinder?",
    ],
  },
  rather: {
    label: "Would You Rather",
    color: "#ec4899",
    easy: [
      "Would you rather fly or be invisible?",
      "Would you rather eat ice cream or cake?",
      "Would you rather play inside or outside?",
      "Would you rather have a pet cat or dog?",
    ],
    medium: [
      "Would you rather visit space or the deep ocean? Why?",
      "Would you rather be very fast or very strong?",
      "Would you rather only read or only draw for a week?",
      "Would you rather live in a treehouse or a boat?",
    ],
    hard: [
      "Would you rather always tell the truth or always be kind? Explain.",
      "Would you rather explore the past or the future? Why?",
      "Would you rather lead a team or be a helpful teammate? Why?",
    ],
  },
};

window.SPINNER_CATS = Object.keys(window.SPINNER_PROMPTS);
