/**
 * Classroom-friendly 20 Questions knowledge base.
 * Each item: name, emoji, category, traits (boolean flags).
 */
window.Q20_ITEMS = [
  // Animals
  { name: "dog", emoji: "🐕", cat: "animal", traits: { alive: true, animal: true, pet: true, mammal: true, flies: false, swims: true, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: true, four_legs: true, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "cat", emoji: "🐈", cat: "animal", traits: { alive: true, animal: true, pet: true, mammal: true, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: true, has_legs: true, four_legs: true, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "bird", emoji: "🐦", cat: "animal", traits: { alive: true, animal: true, pet: true, mammal: false, flies: true, swims: false, farm: false, wild: true, tiny: true, huge: false, predator: false, has_legs: true, four_legs: false, two_legs: true, scales: false, feathers: true, water: false, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "fish", emoji: "🐟", cat: "animal", traits: { alive: true, animal: true, pet: true, mammal: false, flies: false, swims: true, farm: false, wild: true, tiny: true, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: true, feathers: false, water: true, plant: false, food: true, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: false, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "elephant", emoji: "🐘", cat: "animal", traits: { alive: true, animal: true, pet: false, mammal: true, flies: false, swims: true, farm: false, wild: true, tiny: false, huge: true, predator: false, has_legs: true, four_legs: true, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "lion", emoji: "🦁", cat: "animal", traits: { alive: true, animal: true, pet: false, mammal: true, flies: false, swims: false, farm: false, wild: true, tiny: false, huge: false, predator: true, has_legs: true, four_legs: true, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "snake", emoji: "🐍", cat: "animal", traits: { alive: true, animal: true, pet: true, mammal: false, flies: false, swims: true, farm: false, wild: true, tiny: false, huge: false, predator: true, has_legs: false, four_legs: false, two_legs: false, scales: true, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "frog", emoji: "🐸", cat: "animal", traits: { alive: true, animal: true, pet: false, mammal: false, flies: false, swims: true, farm: false, wild: true, tiny: true, huge: false, predator: false, has_legs: true, four_legs: true, two_legs: false, scales: false, feathers: false, water: true, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "cow", emoji: "🐄", cat: "animal", traits: { alive: true, animal: true, pet: false, mammal: true, flies: false, swims: false, farm: true, wild: false, tiny: false, huge: true, predator: false, has_legs: true, four_legs: true, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "butterfly", emoji: "🦋", cat: "animal", traits: { alive: true, animal: true, pet: false, mammal: false, flies: true, swims: false, farm: false, wild: true, tiny: true, huge: false, predator: false, has_legs: true, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "penguin", emoji: "🐧", cat: "animal", traits: { alive: true, animal: true, pet: false, mammal: false, flies: false, swims: true, farm: false, wild: true, tiny: false, huge: false, predator: false, has_legs: true, four_legs: false, two_legs: true, scales: false, feathers: true, water: true, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "rabbit", emoji: "🐰", cat: "animal", traits: { alive: true, animal: true, pet: true, mammal: true, flies: false, swims: false, farm: false, wild: true, tiny: true, huge: false, predator: false, has_legs: true, four_legs: true, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },

  // Food
  { name: "apple", emoji: "🍎", cat: "food", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: true, food: true, sweet: true, tool: false, school: false, read: false, place: false, building: false, outside: false, vehicle: false, electronic: false, round: true, metal: false } },
  { name: "banana", emoji: "🍌", cat: "food", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: true, food: true, sweet: true, tool: false, school: false, read: false, place: false, building: false, outside: false, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "pizza", emoji: "🍕", cat: "food", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: true, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: false, vehicle: false, electronic: false, round: true, metal: false } },
  { name: "ice cream", emoji: "🍦", cat: "food", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: true, sweet: true, tool: false, school: false, read: false, place: false, building: false, outside: false, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "bread", emoji: "🍞", cat: "food", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: true, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: false, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "carrot", emoji: "🥕", cat: "food", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: true, food: true, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: false, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "cheese", emoji: "🧀", cat: "food", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: true, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: false, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "cookie", emoji: "🍪", cat: "food", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: true, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: true, sweet: true, tool: false, school: false, read: false, place: false, building: false, outside: false, vehicle: false, electronic: false, round: true, metal: false } },

  // Objects / school
  { name: "pencil", emoji: "✏️", cat: "object", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: true, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: true, school: true, read: false, place: false, building: false, outside: false, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "book", emoji: "📖", cat: "object", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: true, read: true, place: false, building: false, outside: false, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "scissors", emoji: "✂️", cat: "object", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: true, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: true, school: true, read: false, place: false, building: false, outside: false, vehicle: false, electronic: false, round: false, metal: true } },
  { name: "ball", emoji: "⚽", cat: "object", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: true, vehicle: false, electronic: false, round: true, metal: false } },
  { name: "clock", emoji: "🕐", cat: "object", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: true, read: false, place: false, building: false, outside: false, vehicle: false, electronic: true, round: true, metal: false } },
  { name: "chair", emoji: "🪑", cat: "object", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: true, four_legs: true, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: true, read: false, place: false, building: false, outside: false, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "phone", emoji: "📱", cat: "object", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: true, school: false, read: false, place: false, building: false, outside: false, vehicle: false, electronic: true, round: false, metal: true } },
  { name: "bicycle", emoji: "🚲", cat: "object", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: false, building: false, outside: true, vehicle: true, electronic: false, round: false, metal: true } },
  { name: "umbrella", emoji: "☂️", cat: "object", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: true, school: false, read: false, place: false, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "key", emoji: "🔑", cat: "object", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: true, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: true, school: false, read: false, place: false, building: false, outside: false, vehicle: false, electronic: false, round: false, metal: true } },
  { name: "backpack", emoji: "🎒", cat: "object", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: true, read: false, place: false, building: false, outside: false, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "globe", emoji: "🌍", cat: "object", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: true, read: false, place: false, building: false, outside: false, vehicle: false, electronic: false, round: true, metal: false } },

  // Places
  { name: "school", emoji: "🏫", cat: "place", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: true, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: true, read: false, place: true, building: true, outside: false, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "park", emoji: "🏞️", cat: "place", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: true, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: true, food: false, sweet: false, tool: false, school: false, read: false, place: true, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "beach", emoji: "🏖️", cat: "place", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: true, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: true, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: true, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "library", emoji: "📚", cat: "place", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: true, read: true, place: true, building: true, outside: false, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "zoo", emoji: "🦁", cat: "place", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: true, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: true, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "kitchen", emoji: "🍳", cat: "place", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: false, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: true, sweet: false, tool: false, school: false, read: false, place: true, building: true, outside: false, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "mountain", emoji: "⛰️", cat: "place", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: true, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: true, building: false, outside: true, vehicle: false, electronic: false, round: false, metal: false } },
  { name: "hospital", emoji: "🏥", cat: "place", traits: { alive: false, animal: false, pet: false, mammal: false, flies: false, swims: false, farm: false, wild: false, tiny: false, huge: true, predator: false, has_legs: false, four_legs: false, two_legs: false, scales: false, feathers: false, water: false, plant: false, food: false, sweet: false, tool: false, school: false, read: false, place: true, building: true, outside: false, vehicle: false, electronic: false, round: false, metal: false } },
];

window.Q20_QUESTIONS = [
  { key: "alive", text: "Is it a living thing?" },
  { key: "animal", text: "Is it an animal?" },
  { key: "pet", text: "Could it be a pet?" },
  { key: "mammal", text: "Is it a mammal?" },
  { key: "flies", text: "Can it fly?" },
  { key: "swims", text: "Can it swim?" },
  { key: "farm", text: "Is it often found on a farm?" },
  { key: "wild", text: "Does it usually live in the wild?" },
  { key: "tiny", text: "Is it quite small?" },
  { key: "huge", text: "Is it very large?" },
  { key: "predator", text: "Does it hunt other animals?" },
  { key: "has_legs", text: "Does it have legs?" },
  { key: "four_legs", text: "Does it walk on four legs?" },
  { key: "two_legs", text: "Does it walk on two legs?" },
  { key: "scales", text: "Does it have scales?" },
  { key: "feathers", text: "Does it have feathers?" },
  { key: "water", text: "Is it closely tied to water?" },
  { key: "plant", text: "Does it come from a plant?" },
  { key: "food", text: "Is it something people eat?" },
  { key: "sweet", text: "Does it taste sweet?" },
  { key: "tool", text: "Is it a tool or useful object?" },
  { key: "school", text: "Would you often find it at school?" },
  { key: "read", text: "Is it used for reading or full of words?" },
  { key: "place", text: "Is it a place you can go?" },
  { key: "building", text: "Is it a building?" },
  { key: "outside", text: "Do people mostly use or see it outdoors?" },
  { key: "vehicle", text: "Is it a vehicle you can ride?" },
  { key: "electronic", text: "Does it use electricity or batteries?" },
  { key: "round", text: "Is it mostly round in shape?" },
  { key: "metal", text: "Is it made mostly of metal?" },
];

window.Q20_FLAVOR = [
  "The crystal swirls…",
  "Hmm, the mists shift…",
  "I see shapes forming…",
  "Interesting… very interesting…",
  "The stars whisper something…",
  "Closer now…",
  "My owl nods in agreement…",
  "A vision sharpens…",
  "Fate draws a thread…",
  "Ah… that narrows the path…",
];
