/**
 * 20 Questions knowledge base — classroom-friendly items + yes/no traits.
 */
window.Q20_ITEMS = [
  { name: "dog", emoji: "🐕", cat: "animal", traits: { living:1, animal:1, pet:1, mammal:1, farm:0, wild:0, water_animal:0, flies:0, walks:1, four_legs:1, predator:0, tiny:0, huge:0, stripes:0, barks:1 } },
  { name: "cat", emoji: "🐈", cat: "animal", traits: { living:1, animal:1, pet:1, mammal:1, farm:0, wild:0, water_animal:0, flies:0, walks:1, four_legs:1, predator:1, tiny:0, huge:0, stripes:0, barks:0 } },
  { name: "rabbit", emoji: "🐰", cat: "animal", traits: { living:1, animal:1, pet:1, mammal:1, farm:0, wild:1, water_animal:0, flies:0, walks:1, four_legs:1, predator:0, tiny:1, huge:0, stripes:0, barks:0 } },
  { name: "hamster", emoji: "🐹", cat: "animal", traits: { living:1, animal:1, pet:1, mammal:1, farm:0, wild:0, water_animal:0, flies:0, walks:1, four_legs:1, predator:0, tiny:1, huge:0, stripes:0, barks:0 } },
  { name: "horse", emoji: "🐴", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:1, farm:1, wild:0, water_animal:0, flies:0, walks:1, four_legs:1, predator:0, tiny:0, huge:1, stripes:0, barks:0 } },
  { name: "cow", emoji: "🐄", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:1, farm:1, wild:0, water_animal:0, flies:0, walks:1, four_legs:1, predator:0, tiny:0, huge:1, stripes:0, barks:0 } },
  { name: "pig", emoji: "🐷", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:1, farm:1, wild:0, water_animal:0, flies:0, walks:1, four_legs:1, predator:0, tiny:0, huge:0, stripes:0, barks:0 } },
  { name: "sheep", emoji: "🐑", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:1, farm:1, wild:0, water_animal:0, flies:0, walks:1, four_legs:1, predator:0, tiny:0, huge:0, stripes:0, barks:0 } },
  { name: "chicken", emoji: "🐔", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:0, farm:1, wild:0, water_animal:0, flies:0, walks:1, four_legs:0, predator:0, tiny:0, huge:0, stripes:0, barks:0, bird:1, feathers:1 } },
  { name: "duck", emoji: "🦆", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:0, farm:1, wild:1, water_animal:1, flies:1, walks:1, four_legs:0, predator:0, tiny:0, huge:0, stripes:0, barks:0, bird:1, feathers:1 } },
  { name: "bird", emoji: "🐦", cat: "animal", traits: { living:1, animal:1, pet:1, mammal:0, farm:0, wild:1, water_animal:0, flies:1, walks:1, four_legs:0, predator:0, tiny:1, huge:0, stripes:0, barks:0, bird:1, feathers:1 } },
  { name: "eagle", emoji: "🦅", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:0, farm:0, wild:1, water_animal:0, flies:1, walks:1, four_legs:0, predator:1, tiny:0, huge:0, stripes:0, barks:0, bird:1, feathers:1 } },
  { name: "penguin", emoji: "🐧", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:0, farm:0, wild:1, water_animal:1, flies:0, walks:1, four_legs:0, predator:0, tiny:0, huge:0, stripes:0, barks:0, bird:1, feathers:1 } },
  { name: "fish", emoji: "🐟", cat: "animal", traits: { living:1, animal:1, pet:1, mammal:0, farm:0, wild:1, water_animal:1, flies:0, walks:0, four_legs:0, predator:0, tiny:1, huge:0, stripes:0, barks:0, scales:1 } },
  { name: "shark", emoji: "🦈", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:0, farm:0, wild:1, water_animal:1, flies:0, walks:0, four_legs:0, predator:1, tiny:0, huge:1, stripes:0, barks:0, scales:1 } },
  { name: "whale", emoji: "🐋", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:1, farm:0, wild:1, water_animal:1, flies:0, walks:0, four_legs:0, predator:0, tiny:0, huge:1, stripes:0, barks:0 } },
  { name: "dolphin", emoji: "🐬", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:1, farm:0, wild:1, water_animal:1, flies:0, walks:0, four_legs:0, predator:0, tiny:0, huge:0, stripes:0, barks:0 } },
  { name: "frog", emoji: "🐸", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:0, farm:0, wild:1, water_animal:1, flies:0, walks:1, four_legs:1, predator:0, tiny:1, huge:0, stripes:0, barks:0 } },
  { name: "snake", emoji: "🐍", cat: "animal", traits: { living:1, animal:1, pet:1, mammal:0, farm:0, wild:1, water_animal:0, flies:0, walks:0, four_legs:0, predator:1, tiny:0, huge:0, stripes:0, barks:0, scales:1 } },
  { name: "turtle", emoji: "🐢", cat: "animal", traits: { living:1, animal:1, pet:1, mammal:0, farm:0, wild:1, water_animal:1, flies:0, walks:1, four_legs:1, predator:0, tiny:0, huge:0, stripes:0, barks:0, shell:1 } },
  { name: "lion", emoji: "🦁", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:1, farm:0, wild:1, water_animal:0, flies:0, walks:1, four_legs:1, predator:1, tiny:0, huge:0, stripes:0, barks:0, mane:1 } },
  { name: "tiger", emoji: "🐯", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:1, farm:0, wild:1, water_animal:0, flies:0, walks:1, four_legs:1, predator:1, tiny:0, huge:0, stripes:1, barks:0 } },
  { name: "elephant", emoji: "🐘", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:1, farm:0, wild:1, water_animal:0, flies:0, walks:1, four_legs:1, predator:0, tiny:0, huge:1, stripes:0, barks:0, trunk:1 } },
  { name: "bear", emoji: "🐻", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:1, farm:0, wild:1, water_animal:0, flies:0, walks:1, four_legs:1, predator:1, tiny:0, huge:1, stripes:0, barks:0 } },
  { name: "monkey", emoji: "🐵", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:1, farm:0, wild:1, water_animal:0, flies:0, walks:1, four_legs:0, predator:0, tiny:0, huge:0, stripes:0, barks:0, climbs:1 } },
  { name: "butterfly", emoji: "🦋", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:0, farm:0, wild:1, water_animal:0, flies:1, walks:0, four_legs:0, predator:0, tiny:1, huge:0, stripes:0, barks:0, insect:1 } },
  { name: "bee", emoji: "🐝", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:0, farm:0, wild:1, water_animal:0, flies:1, walks:0, four_legs:0, predator:0, tiny:1, huge:0, stripes:1, barks:0, insect:1 } },
  { name: "spider", emoji: "🕷️", cat: "animal", traits: { living:1, animal:1, pet:0, mammal:0, farm:0, wild:1, water_animal:0, flies:0, walks:1, four_legs:0, predator:1, tiny:1, huge:0, stripes:0, barks:0, eight_legs:1 } },

  { name: "apple", emoji: "🍎", cat: "food", traits: { living:0, food:1, fruit:1, vegetable:0, sweet:1, hot_food:0, cold_food:0, drink:0, breakfast:0, round:1, yellow:0, red:1, from_plant:1, dairy:0, meat:0, baked:0 } },
  { name: "banana", emoji: "🍌", cat: "food", traits: { living:0, food:1, fruit:1, vegetable:0, sweet:1, hot_food:0, cold_food:0, drink:0, breakfast:1, round:0, yellow:1, red:0, from_plant:1, dairy:0, meat:0, baked:0 } },
  { name: "orange", emoji: "🍊", cat: "food", traits: { living:0, food:1, fruit:1, vegetable:0, sweet:1, hot_food:0, cold_food:0, drink:0, breakfast:0, round:1, yellow:0, red:0, from_plant:1, dairy:0, meat:0, baked:0, orange_color:1 } },
  { name: "grape", emoji: "🍇", cat: "food", traits: { living:0, food:1, fruit:1, vegetable:0, sweet:1, hot_food:0, cold_food:0, drink:0, breakfast:0, round:1, yellow:0, red:0, from_plant:1, dairy:0, meat:0, baked:0, tiny_food:1 } },
  { name: "carrot", emoji: "🥕", cat: "food", traits: { living:0, food:1, fruit:0, vegetable:1, sweet:0, hot_food:0, cold_food:0, drink:0, breakfast:0, round:0, yellow:0, red:0, from_plant:1, dairy:0, meat:0, baked:0, orange_color:1 } },
  { name: "broccoli", emoji: "🥦", cat: "food", traits: { living:0, food:1, fruit:0, vegetable:1, sweet:0, hot_food:0, cold_food:0, drink:0, breakfast:0, round:0, yellow:0, red:0, from_plant:1, dairy:0, meat:0, baked:0, green_food:1 } },
  { name: "pizza", emoji: "🍕", cat: "food", traits: { living:0, food:1, fruit:0, vegetable:0, sweet:0, hot_food:1, cold_food:0, drink:0, breakfast:0, round:1, yellow:0, red:0, from_plant:0, dairy:0, meat:0, baked:1 } },
  { name: "burger", emoji: "🍔", cat: "food", traits: { living:0, food:1, fruit:0, vegetable:0, sweet:0, hot_food:1, cold_food:0, drink:0, breakfast:0, round:1, yellow:0, red:0, from_plant:0, dairy:0, meat:1, baked:0 } },
  { name: "bread", emoji: "🍞", cat: "food", traits: { living:0, food:1, fruit:0, vegetable:0, sweet:0, hot_food:0, cold_food:0, drink:0, breakfast:1, round:0, yellow:0, red:0, from_plant:1, dairy:0, meat:0, baked:1 } },
  { name: "cheese", emoji: "🧀", cat: "food", traits: { living:0, food:1, fruit:0, vegetable:0, sweet:0, hot_food:0, cold_food:0, drink:0, breakfast:0, round:0, yellow:1, red:0, from_plant:0, dairy:1, meat:0, baked:0 } },
  { name: "milk", emoji: "🥛", cat: "food", traits: { living:0, food:1, fruit:0, vegetable:0, sweet:0, hot_food:0, cold_food:1, drink:1, breakfast:1, round:0, yellow:0, red:0, from_plant:0, dairy:1, meat:0, baked:0 } },
  { name: "juice", emoji: "🧃", cat: "food", traits: { living:0, food:1, fruit:1, vegetable:0, sweet:1, hot_food:0, cold_food:1, drink:1, breakfast:1, round:0, yellow:0, red:0, from_plant:1, dairy:0, meat:0, baked:0 } },
  { name: "ice cream", emoji: "🍦", cat: "food", traits: { living:0, food:1, fruit:0, vegetable:0, sweet:1, hot_food:0, cold_food:1, drink:0, breakfast:0, round:0, yellow:0, red:0, from_plant:0, dairy:1, meat:0, baked:0 } },
  { name: "cookie", emoji: "🍪", cat: "food", traits: { living:0, food:1, fruit:0, vegetable:0, sweet:1, hot_food:0, cold_food:0, drink:0, breakfast:0, round:1, yellow:0, red:0, from_plant:0, dairy:0, meat:0, baked:1, tiny_food:1 } },
  { name: "cake", emoji: "🎂", cat: "food", traits: { living:0, food:1, fruit:0, vegetable:0, sweet:1, hot_food:0, cold_food:0, drink:0, breakfast:0, round:1, yellow:0, red:0, from_plant:0, dairy:0, meat:0, baked:1 } },
  { name: "egg", emoji: "🥚", cat: "food", traits: { living:0, food:1, fruit:0, vegetable:0, sweet:0, hot_food:1, cold_food:0, drink:0, breakfast:1, round:1, yellow:0, red:0, from_plant:0, dairy:0, meat:0, baked:0 } },
  { name: "rice", emoji: "🍚", cat: "food", traits: { living:0, food:1, fruit:0, vegetable:0, sweet:0, hot_food:1, cold_food:0, drink:0, breakfast:0, round:0, yellow:0, red:0, from_plant:1, dairy:0, meat:0, baked:0 } },
  { name: "noodles", emoji: "🍜", cat: "food", traits: { living:0, food:1, fruit:0, vegetable:0, sweet:0, hot_food:1, cold_food:0, drink:0, breakfast:0, round:0, yellow:0, red:0, from_plant:1, dairy:0, meat:0, baked:0 } },

  { name: "pencil", emoji: "✏️", cat: "object", traits: { living:0, object:1, school:1, tool:1, electronic:0, metal:0, paper:0, write:1, read:0, wear:0, play:0, round:0, tiny:1, furniture:0, container:0, cut:0, light:0 } },
  { name: "pen", emoji: "🖊️", cat: "object", traits: { living:0, object:1, school:1, tool:1, electronic:0, metal:0, paper:0, write:1, read:0, wear:0, play:0, round:0, tiny:1, furniture:0, container:0, cut:0, light:0 } },
  { name: "book", emoji: "📖", cat: "object", traits: { living:0, object:1, school:1, tool:0, electronic:0, metal:0, paper:1, write:0, read:1, wear:0, play:0, round:0, tiny:0, furniture:0, container:0, cut:0, light:0 } },
  { name: "notebook", emoji: "📓", cat: "object", traits: { living:0, object:1, school:1, tool:0, electronic:0, metal:0, paper:1, write:1, read:0, wear:0, play:0, round:0, tiny:0, furniture:0, container:0, cut:0, light:0 } },
  { name: "scissors", emoji: "✂️", cat: "object", traits: { living:0, object:1, school:1, tool:1, electronic:0, metal:1, paper:0, write:0, read:0, wear:0, play:0, round:0, tiny:1, furniture:0, container:0, cut:1, light:0 } },
  { name: "ruler", emoji: "📏", cat: "object", traits: { living:0, object:1, school:1, tool:1, electronic:0, metal:0, paper:0, write:0, read:0, wear:0, play:0, round:0, tiny:0, furniture:0, container:0, cut:0, light:0, measure:1 } },
  { name: "backpack", emoji: "🎒", cat: "object", traits: { living:0, object:1, school:1, tool:0, electronic:0, metal:0, paper:0, write:0, read:0, wear:1, play:0, round:0, tiny:0, furniture:0, container:1, cut:0, light:0 } },
  { name: "chair", emoji: "🪑", cat: "object", traits: { living:0, object:1, school:1, tool:0, electronic:0, metal:0, paper:0, write:0, read:0, wear:0, play:0, round:0, tiny:0, furniture:1, container:0, cut:0, light:0 } },
  { name: "table", emoji: "🪵", cat: "object", traits: { living:0, object:1, school:1, tool:0, electronic:0, metal:0, paper:0, write:0, read:0, wear:0, play:0, round:0, tiny:0, furniture:1, container:0, cut:0, light:0 } },
  { name: "ball", emoji: "⚽", cat: "object", traits: { living:0, object:1, school:0, tool:0, electronic:0, metal:0, paper:0, write:0, read:0, wear:0, play:1, round:1, tiny:0, furniture:0, container:0, cut:0, light:0 } },
  { name: "kite", emoji: "🪁", cat: "object", traits: { living:0, object:1, school:0, tool:0, electronic:0, metal:0, paper:0, write:0, read:0, wear:0, play:1, round:0, tiny:0, furniture:0, container:0, cut:0, light:0, flies_obj:1 } },
  { name: "phone", emoji: "📱", cat: "object", traits: { living:0, object:1, school:0, tool:1, electronic:1, metal:1, paper:0, write:0, read:0, wear:0, play:0, round:0, tiny:0, furniture:0, container:0, cut:0, light:1 } },
  { name: "computer", emoji: "💻", cat: "object", traits: { living:0, object:1, school:1, tool:1, electronic:1, metal:1, paper:0, write:0, read:0, wear:0, play:0, round:0, tiny:0, furniture:0, container:0, cut:0, light:1 } },
  { name: "clock", emoji: "🕐", cat: "object", traits: { living:0, object:1, school:1, tool:0, electronic:1, metal:0, paper:0, write:0, read:0, wear:0, play:0, round:1, tiny:0, furniture:0, container:0, cut:0, light:0, time:1 } },
  { name: "lamp", emoji: "💡", cat: "object", traits: { living:0, object:1, school:0, tool:0, electronic:1, metal:0, paper:0, write:0, read:0, wear:0, play:0, round:0, tiny:0, furniture:0, container:0, cut:0, light:1 } },
  { name: "key", emoji: "🔑", cat: "object", traits: { living:0, object:1, school:0, tool:1, electronic:0, metal:1, paper:0, write:0, read:0, wear:0, play:0, round:0, tiny:1, furniture:0, container:0, cut:0, light:0 } },
  { name: "umbrella", emoji: "☂️", cat: "object", traits: { living:0, object:1, school:0, tool:1, electronic:0, metal:0, paper:0, write:0, read:0, wear:0, play:0, round:0, tiny:0, furniture:0, container:0, cut:0, light:0, rain:1 } },
  { name: "bicycle", emoji: "🚲", cat: "object", traits: { living:0, object:1, school:0, tool:0, electronic:0, metal:1, paper:0, write:0, read:0, wear:0, play:0, round:0, tiny:0, furniture:0, container:0, cut:0, light:0, vehicle:1 } },
  { name: "car", emoji: "🚗", cat: "object", traits: { living:0, object:1, school:0, tool:0, electronic:0, metal:1, paper:0, write:0, read:0, wear:0, play:0, round:0, tiny:0, furniture:0, container:0, cut:0, light:0, vehicle:1 } },
  { name: "globe", emoji: "🌍", cat: "object", traits: { living:0, object:1, school:1, tool:0, electronic:0, metal:0, paper:0, write:0, read:0, wear:0, play:0, round:1, tiny:0, furniture:0, container:0, cut:0, light:0 } },
  { name: "cup", emoji: "☕", cat: "object", traits: { living:0, object:1, school:0, tool:0, electronic:0, metal:0, paper:0, write:0, read:0, wear:0, play:0, round:1, tiny:0, furniture:0, container:1, cut:0, light:0 } },
  { name: "hat", emoji: "🎩", cat: "object", traits: { living:0, object:1, school:0, tool:0, electronic:0, metal:0, paper:0, write:0, read:0, wear:1, play:0, round:0, tiny:0, furniture:0, container:0, cut:0, light:0 } },
  { name: "shoes", emoji: "👟", cat: "object", traits: { living:0, object:1, school:0, tool:0, electronic:0, metal:0, paper:0, write:0, read:0, wear:1, play:0, round:0, tiny:0, furniture:0, container:0, cut:0, light:0 } },

  { name: "school", emoji: "🏫", cat: "place", traits: { living:0, place:1, building:1, outside:0, water_place:0, learn:1, animals_place:0, play_place:0, food_place:0, sleep_place:0, nature:0, city:0, tall:0 } },
  { name: "library", emoji: "📚", cat: "place", traits: { living:0, place:1, building:1, outside:0, water_place:0, learn:1, animals_place:0, play_place:0, food_place:0, sleep_place:0, nature:0, city:0, tall:0, quiet:1 } },
  { name: "hospital", emoji: "🏥", cat: "place", traits: { living:0, place:1, building:1, outside:0, water_place:0, learn:0, animals_place:0, play_place:0, food_place:0, sleep_place:0, nature:0, city:1, tall:0, medical:1 } },
  { name: "kitchen", emoji: "🍳", cat: "place", traits: { living:0, place:1, building:1, outside:0, water_place:0, learn:0, animals_place:0, play_place:0, food_place:1, sleep_place:0, nature:0, city:0, tall:0 } },
  { name: "bedroom", emoji: "🛏️", cat: "place", traits: { living:0, place:1, building:1, outside:0, water_place:0, learn:0, animals_place:0, play_place:0, food_place:0, sleep_place:1, nature:0, city:0, tall:0 } },
  { name: "park", emoji: "🏞️", cat: "place", traits: { living:0, place:1, building:0, outside:1, water_place:0, learn:0, animals_place:0, play_place:1, food_place:0, sleep_place:0, nature:1, city:0, tall:0 } },
  { name: "beach", emoji: "🏖️", cat: "place", traits: { living:0, place:1, building:0, outside:1, water_place:1, learn:0, animals_place:0, play_place:1, food_place:0, sleep_place:0, nature:1, city:0, tall:0 } },
  { name: "zoo", emoji: "🦒", cat: "place", traits: { living:0, place:1, building:0, outside:1, water_place:0, learn:0, animals_place:1, play_place:0, food_place:0, sleep_place:0, nature:0, city:0, tall:0 } },
  { name: "farm", emoji: "🚜", cat: "place", traits: { living:0, place:1, building:0, outside:1, water_place:0, learn:0, animals_place:1, play_place:0, food_place:1, sleep_place:0, nature:1, city:0, tall:0 } },
  { name: "mountain", emoji: "⛰️", cat: "place", traits: { living:0, place:1, building:0, outside:1, water_place:0, learn:0, animals_place:0, play_place:0, food_place:0, sleep_place:0, nature:1, city:0, tall:1 } },
  { name: "forest", emoji: "🌲", cat: "place", traits: { living:0, place:1, building:0, outside:1, water_place:0, learn:0, animals_place:1, play_place:0, food_place:0, sleep_place:0, nature:1, city:0, tall:0 } },
  { name: "city", emoji: "🏙️", cat: "place", traits: { living:0, place:1, building:1, outside:1, water_place:0, learn:0, animals_place:0, play_place:0, food_place:0, sleep_place:0, nature:0, city:1, tall:1 } },
  { name: "museum", emoji: "🏛️", cat: "place", traits: { living:0, place:1, building:1, outside:0, water_place:0, learn:1, animals_place:0, play_place:0, food_place:0, sleep_place:0, nature:0, city:1, tall:0 } },
  { name: "playground", emoji: "🛝", cat: "place", traits: { living:0, place:1, building:0, outside:1, water_place:0, learn:0, animals_place:0, play_place:1, food_place:0, sleep_place:0, nature:0, city:0, tall:0 } },
  { name: "swimming pool", emoji: "🏊", cat: "place", traits: { living:0, place:1, building:0, outside:0, water_place:1, learn:0, animals_place:0, play_place:1, food_place:0, sleep_place:0, nature:0, city:0, tall:0 } },
];

window.Q20_QUESTIONS = [
  { key: "living", text: "Is it a living thing?" },
  { key: "animal", text: "Is it an animal?" },
  { key: "food", text: "Is it something people eat or drink?" },
  { key: "object", text: "Is it an object you can hold or use?" },
  { key: "place", text: "Is it a place you can go?" },
  { key: "pet", text: "Is it commonly kept as a pet?" },
  { key: "mammal", text: "Is it a mammal?" },
  { key: "bird", text: "Is it a bird?" },
  { key: "insect", text: "Is it an insect?" },
  { key: "farm", text: "Is it often found on a farm?" },
  { key: "wild", text: "Does it usually live in the wild?" },
  { key: "water_animal", text: "Does it live in or around water?" },
  { key: "flies", text: "Can it fly?" },
  { key: "walks", text: "Does it walk on land?" },
  { key: "four_legs", text: "Does it have four legs?" },
  { key: "predator", text: "Does it hunt other animals for food?" },
  { key: "tiny", text: "Is it very small?" },
  { key: "huge", text: "Is it very large?" },
  { key: "scales", text: "Does it have scales?" },
  { key: "feathers", text: "Does it have feathers?" },
  { key: "stripes", text: "Does it have stripes?" },
  { key: "shell", text: "Does it have a hard shell?" },
  { key: "trunk", text: "Does it have a trunk?" },
  { key: "mane", text: "Does it have a mane?" },
  { key: "climbs", text: "Is it known for climbing?" },
  { key: "eight_legs", text: "Does it have eight legs?" },
  { key: "barks", text: "Does it bark?" },
  { key: "fruit", text: "Is it a fruit?" },
  { key: "vegetable", text: "Is it a vegetable?" },
  { key: "sweet", text: "Is it sweet?" },
  { key: "drink", text: "Is it a drink?" },
  { key: "hot_food", text: "Is it usually eaten hot?" },
  { key: "cold_food", text: "Is it usually cold when you have it?" },
  { key: "breakfast", text: "Do people often have it at breakfast?" },
  { key: "dairy", text: "Is it a dairy food?" },
  { key: "meat", text: "Does it usually contain meat?" },
  { key: "baked", text: "Is it something baked?" },
  { key: "from_plant", text: "Does it come from a plant?" },
  { key: "round", text: "Is it mostly round?" },
  { key: "yellow", text: "Is it mostly yellow?" },
  { key: "red", text: "Is it mostly red?" },
  { key: "orange_color", text: "Is it orange in color?" },
  { key: "green_food", text: "Is it green?" },
  { key: "tiny_food", text: "Is each piece quite small?" },
  { key: "school", text: "Would you often find it at school?" },
  { key: "tool", text: "Is it a tool that helps you do a job?" },
  { key: "electronic", text: "Does it use electricity or batteries?" },
  { key: "metal", text: "Is it made mostly of metal?" },
  { key: "paper", text: "Is it made mostly of paper?" },
  { key: "write", text: "Do you use it for writing?" },
  { key: "read", text: "Do you read it?" },
  { key: "wear", text: "Do people wear it?" },
  { key: "play", text: "Is it mainly for play or sports?" },
  { key: "furniture", text: "Is it furniture?" },
  { key: "container", text: "Does it hold or carry things?" },
  { key: "cut", text: "Is it used for cutting?" },
  { key: "light", text: "Does it make light or show a screen?" },
  { key: "vehicle", text: "Is it a vehicle?" },
  { key: "time", text: "Does it tell the time?" },
  { key: "measure", text: "Is it used for measuring?" },
  { key: "rain", text: "Is it used when it rains?" },
  { key: "flies_obj", text: "Does it fly in the sky when you use it?" },
  { key: "building", text: "Is it a building?" },
  { key: "outside", text: "Is it mainly outdoors?" },
  { key: "water_place", text: "Is water an important part of this place?" },
  { key: "learn", text: "Is it a place for learning?" },
  { key: "animals_place", text: "Are animals a big part of this place?" },
  { key: "play_place", text: "Is it mainly for play?" },
  { key: "food_place", text: "Is food a big part of this place?" },
  { key: "sleep_place", text: "Is it a place for sleeping?" },
  { key: "nature", text: "Is it a natural place (not mostly man-made)?" },
  { key: "city", text: "Is it found in a city?" },
  { key: "tall", text: "Is it known for being tall or high up?" },
  { key: "quiet", text: "Is it usually a quiet place?" },
  { key: "medical", text: "Is it related to health or doctors?" },
];

window.Q20_FLAVOR = [
  "The crystal swirls…",
  "Hmm, the mists shift…",
  "I see shapes forming…",
  "Interesting… very interesting…",
  "The stars whisper something…",
  "Closer now…",
  "A vision sharpens…",
  "Fate draws a thread…",
  "Ah… that narrows the path…",
  "Yes… the pattern emerges…",
];
