/**
 * 20 public-domain classic tales / fables — classroom sequencing adaptations.
 * Short original wording for education; plots from PD sources (Aesop, folk tradition, Andersen, etc.).
 */
window.STORY_SEQUENCE_DATA = [
  {
    id: "tortoise-hare",
    title: "The Tortoise and the Hare",
    origin: "Aesop",
    panels: [
      { emoji: "🐰😤", text: "A proud hare laughs at a slow tortoise." },
      { emoji: "🏁🐢", text: "They start a race. The hare dashes ahead." },
      { emoji: "😴🌳", text: "The hare naps, sure he will win easily." },
      { emoji: "🐢🏆", text: "The tortoise keeps going and crosses first." },
    ],
    sentences: [
      "A hare teased a tortoise for being slow.",
      "They agreed to race across the field.",
      "The hare slept under a tree mid-race.",
      "The steady tortoise won while the hare slept.",
    ],
  },
  {
    id: "cried-wolf",
    title: "The Boy Who Cried Wolf",
    origin: "Aesop",
    panels: [
      { emoji: "👦📣", text: "A shepherd boy shouts that a wolf is coming." },
      { emoji: "🏃‍♂️😅", text: "Villagers run to help — but there is no wolf." },
      { emoji: "👦😂", text: "The boy laughs. He tricks them again." },
      { emoji: "🐺😱", text: "A real wolf comes. No one believes his cries." },
    ],
    sentences: [
      "A boy watched sheep and grew bored.",
      "He cried “Wolf!” and the villagers came running.",
      "He tricked them more than once for fun.",
      "When a real wolf came, nobody listened.",
    ],
  },
  {
    id: "ant-grasshopper",
    title: "The Ant and the Grasshopper",
    origin: "Aesop",
    panels: [
      { emoji: "🐜📦", text: "All summer the ant stores food." },
      { emoji: "🦗🎵", text: "The grasshopper sings and plays." },
      { emoji: "❄️🦗", text: "Winter comes. The grasshopper is hungry." },
      { emoji: "🐜🚪", text: "He asks the ant for help and learns a lesson." },
    ],
    sentences: [
      "An ant worked hard gathering food in summer.",
      "A grasshopper spent the season singing.",
      "Cold winter left the grasshopper with nothing.",
      "The ant had prepared; the grasshopper had not.",
    ],
  },
  {
    id: "lion-mouse",
    title: "The Lion and the Mouse",
    origin: "Aesop",
    panels: [
      { emoji: "🦁😠", text: "A lion catches a tiny mouse." },
      { emoji: "🐭🙏", text: "The mouse begs to be freed and promises help." },
      { emoji: "🦁🕸️", text: "Later the lion is trapped in a hunter’s net." },
      { emoji: "🐭✂️", text: "The mouse gnaws the ropes and frees the lion." },
    ],
    sentences: [
      "A mouse woke a sleeping lion.",
      "The lion let the mouse go after a plea.",
      "Hunters trapped the lion in a net.",
      "The grateful mouse chewed the ropes free.",
    ],
  },
  {
    id: "crow-pitcher",
    title: "The Crow and the Pitcher",
    origin: "Aesop",
    panels: [
      { emoji: "🐦💧", text: "A thirsty crow finds a pitcher of water." },
      { emoji: "😣🫙", text: "The water is too low for its beak to reach." },
      { emoji: "🪨➕", text: "The crow drops stones into the pitcher." },
      { emoji: "🐦😋", text: "The water rises and the crow can drink." },
    ],
    sentences: [
      "A crow needed water on a hot day.",
      "It found a pitcher but could not reach the water.",
      "It dropped stones in one by one.",
      "The water rose high enough to drink.",
    ],
  },
  {
    id: "dog-reflection",
    title: "The Dog and His Reflection",
    origin: "Aesop",
    panels: [
      { emoji: "🐕🥩", text: "A dog carries a bone across a bridge." },
      { emoji: "🌊👀", text: "He sees his reflection in the water." },
      { emoji: "🐕😤", text: "He thinks another dog has a bigger bone." },
      { emoji: "💦😢", text: "He snaps at it and loses his own bone." },
    ],
    sentences: [
      "A dog trotted home with a bone.",
      "On a bridge he saw his reflection.",
      "He growled at the “other dog” for its bone.",
      "When he opened his mouth, his bone fell in.",
    ],
  },
  {
    id: "fox-grapes",
    title: "The Fox and the Grapes",
    origin: "Aesop",
    panels: [
      { emoji: "🦊🍇", text: "A fox spots juicy grapes on a high vine." },
      { emoji: "🦊⬆️", text: "He jumps again and again to reach them." },
      { emoji: "😤🚫", text: "He cannot get the grapes." },
      { emoji: "🦊🚶", text: "He walks off saying they were probably sour." },
    ],
    sentences: [
      "A fox wanted grapes hanging high above.",
      "He leapt many times but could not reach.",
      "Tired and cross, he gave up.",
      "He told himself the grapes were sour anyway.",
    ],
  },
  {
    id: "town-country-mouse",
    title: "The Town Mouse and the Country Mouse",
    origin: "Aesop",
    panels: [
      { emoji: "🐭🌾", text: "A country mouse shares simple food at home." },
      { emoji: "🏙️🐭", text: "A town mouse invites him to the city." },
      { emoji: "🧀😱", text: "Fancy food appears — then a cat or dog scares them." },
      { emoji: "🐭🏡", text: "The country mouse chooses quiet safety at home." },
    ],
    sentences: [
      "A country mouse hosted his city cousin.",
      "The town mouse showed off rich city food.",
      "Danger interrupted their feast again and again.",
      "The country mouse preferred simple, safe life.",
    ],
  },
  {
    id: "wind-sun",
    title: "The Wind and the Sun",
    origin: "Aesop",
    panels: [
      { emoji: "💨☀️", text: "Wind and Sun argue over who is stronger." },
      { emoji: "🧥🚶", text: "They spy a traveler wearing a coat." },
      { emoji: "💨🥶", text: "The Wind blows hard; the traveler holds tighter." },
      { emoji: "☀️😊", text: "The Sun shines warmly; the coat comes off." },
    ],
    sentences: [
      "The Wind and the Sun competed for strength.",
      "They tried to remove a traveler’s coat.",
      "Fierce wind only made him grip it tighter.",
      "Gentle sunshine made him take the coat off.",
    ],
  },
  {
    id: "belling-cat",
    title: "Belling the Cat",
    origin: "Aesop",
    panels: [
      { emoji: "🐁😟", text: "Mice meet about the dangerous cat." },
      { emoji: "💡🔔", text: "One mouse suggests putting a bell on the cat." },
      { emoji: "👏🎉", text: "Everyone loves the clever idea." },
      { emoji: "❓🐱", text: "Then someone asks: who will bell the cat?" },
    ],
    sentences: [
      "The mice held a meeting about the cat.",
      "A plan was offered: hang a bell on the cat.",
      "The mice cheered the brilliant idea.",
      "No one volunteered to place the bell.",
    ],
  },
  {
    id: "goldilocks",
    title: "Goldilocks and the Three Bears",
    origin: "English fairy tale (public domain)",
    panels: [
      { emoji: "👧🏠", text: "Goldilocks enters the bears’ empty house." },
      { emoji: "🥣😮", text: "She tastes porridge and sits in the chairs." },
      { emoji: "🛏️😴", text: "She falls asleep in the smallest bed." },
      { emoji: "🐻😱", text: "The bears return and she runs away." },
    ],
    sentences: [
      "Goldilocks found a house in the woods.",
      "She tried the porridge, chairs, and beds.",
      "She fell asleep in Baby Bear’s bed.",
      "The three bears came home and startled her.",
    ],
  },
  {
    id: "three-pigs",
    title: "The Three Little Pigs",
    origin: "English fairy tale (public domain)",
    panels: [
      { emoji: "🐷🌾", text: "One pig builds a house of straw." },
      { emoji: "🐷🪵", text: "Another builds with sticks." },
      { emoji: "🐷🧱", text: "The third builds a strong brick house." },
      { emoji: "🐺💨", text: "The wolf blows hard, but the brick house stands." },
    ],
    sentences: [
      "Three pigs each built a house.",
      "Straw and stick houses were weak.",
      "The brick house was built with care.",
      "The wolf could not blow the brick house down.",
    ],
  },
  {
    id: "little-red",
    title: "Little Red Riding Hood",
    origin: "European fairy tale (public domain)",
    panels: [
      { emoji: "👧🧺", text: "A girl in red takes food to Grandma." },
      { emoji: "🐺🌲", text: "A wolf learns where she is going." },
      { emoji: "🐺👵", text: "The wolf reaches Grandma’s house first." },
      { emoji: "😲🛏️", text: "The girl notices strange “Grandma” features." },
    ],
    sentences: [
      "Little Red brought a basket to Grandma.",
      "She met a wolf along the forest path.",
      "The wolf arrived at Grandma’s house first.",
      "The girl saw that something was very wrong.",
    ],
  },
  {
    id: "gingerbread",
    title: "The Gingerbread Man",
    origin: "American folk tale (public domain)",
    panels: [
      { emoji: "🍪🏃", text: "A gingerbread man jumps up and runs away." },
      { emoji: "👴👵🐕", text: "People and animals chase him." },
      { emoji: "🦊😊", text: "A fox offers to help him cross a river." },
      { emoji: "🦊💦", text: "The fox tricks him — the cookie’s run ends." },
    ],
    sentences: [
      "A gingerbread man came alive and fled.",
      "Many chasers could not catch him.",
      "A fox offered a ride across the water.",
      "The clever fox outsmarted the cookie.",
    ],
  },
  {
    id: "stone-soup",
    title: "Stone Soup",
    origin: "European folk tale (public domain)",
    panels: [
      { emoji: "🧳", text: "Hungry travelers arrive in a village." },
      { emoji: "🪨🍲", text: "They boil a stone in a pot of water." },
      { emoji: "🥕➕", text: "Villagers add vegetables and more." },
      { emoji: "🏘️😋", text: "Everyone shares a fine soup together." },
    ],
    sentences: [
      "Travelers asked villagers for food.",
      "They began soup with only water and a stone.",
      "Curious villagers added real ingredients.",
      "The whole village shared the finished soup.",
    ],
  },
  {
    id: "red-hen",
    title: "The Little Red Hen",
    origin: "Folk tale (public domain)",
    panels: [
      { emoji: "🐔🌾", text: "A hen finds wheat and asks for help planting." },
      { emoji: "🙅‍♂️🙅", text: "The other animals refuse each chore." },
      { emoji: "🍞🔥", text: "She grows, harvests, and bakes bread alone." },
      { emoji: "🐔🍞", text: "She eats the bread; the others get none." },
    ],
    sentences: [
      "The little red hen found some wheat.",
      "Friends would not help her work.",
      "She did every step by herself.",
      "Only she enjoyed the fresh bread.",
    ],
  },
  {
    id: "henny-penny",
    title: "Henny Penny",
    origin: "Folk tale (public domain)",
    panels: [
      { emoji: "🐔🌰", text: "An acorn hits Henny Penny’s head." },
      { emoji: "😱☁️", text: "She thinks the sky is falling." },
      { emoji: "🐦🦆", text: "Friends join her to tell the king." },
      { emoji: "🦊😈", text: "A fox leads them the wrong way." },
    ],
    sentences: [
      "Something small hit Henny Penny’s head.",
      "She feared the sky was falling.",
      "Friends followed her to warn the king.",
      "A fox tricked the frightened birds.",
    ],
  },
  {
    id: "ugly-duckling",
    title: "The Ugly Duckling",
    origin: "Hans Christian Andersen (public domain)",
    panels: [
      { emoji: "🐣😔", text: "A duckling looks different from the others." },
      { emoji: "😢🚶", text: "He is teased and wanders alone." },
      { emoji: "❄️🦆", text: "He survives a hard winter." },
      { emoji: "🦢✨", text: "In spring he becomes a beautiful swan." },
    ],
    sentences: [
      "A duckling did not look like his brothers.",
      "Unkind words sent him away.",
      "He struggled through cold seasons.",
      "He grew into a graceful swan.",
    ],
  },
  {
    id: "emperors-clothes",
    title: "The Emperor’s New Clothes",
    origin: "Hans Christian Andersen (public domain)",
    panels: [
      { emoji: "👑🧵", text: "Weavers claim to make magical invisible cloth." },
      { emoji: "👔🙈", text: "Adults pretend they can see the fine clothes." },
      { emoji: "🚶‍♂️👑", text: "The emperor parades in “new” clothes." },
      { emoji: "👶💬", text: "A child says aloud that he wears nothing." },
    ],
    sentences: [
      "Tricksters promised magical fabric.",
      "People feared seeming foolish, so they lied.",
      "The emperor marched in a grand parade.",
      "A child spoke the simple truth.",
    ],
  },
  {
    id: "jack-beanstalk",
    title: "Jack and the Beanstalk",
    origin: "English fairy tale (public domain)",
    panels: [
      { emoji: "🌱💰", text: "Jack trades a cow for magic beans." },
      { emoji: "🪴☁️", text: "A huge beanstalk grows into the sky." },
      { emoji: "🏰", text: "Jack climbs and finds a giant’s castle." },
      { emoji: "🏃‍♂️🪓", text: "He escapes and cuts the beanstalk down." },
    ],
    sentences: [
      "Jack sold the cow for strange beans.",
      "Overnight a beanstalk reached the clouds.",
      "Jack climbed to a giant’s home.",
      "He fled and chopped the stalk to safety.",
    ],
  },
];
