/**
 * Auto-generated from assets/tts/voices/en_GB — do not hand-edit paths.
 * Regenerate by scanning the voices folder if models change.
 */
(function (global) {
  const VOICES = [
  {
    "id": "en_GB-alan-low",
    "name": "Alan",
    "label": "Alan \u2014 Soft",
    "locale": "en-GB",
    "region": "UK",
    "gender": "male",
    "quality": "low",
    "family": "alan",
    "modelPath": "assets/tts/voices/en_GB/alan/low/en_GB-alan-low.onnx",
    "configPath": "assets/tts/voices/en_GB/alan/low/en_GB-alan-low.onnx.json",
    "sizeBytes": 63104526,
    "license": "MIT",
    "attribution": "Rhasspy Piper / alan",
    "source": "https://huggingface.co/rhasspy/piper-voices"
  },
  {
    "id": "en_GB-alan-medium",
    "name": "Alan",
    "label": "Alan \u2014 Clear",
    "locale": "en-GB",
    "region": "UK",
    "gender": "male",
    "quality": "medium",
    "family": "alan",
    "modelPath": "assets/tts/voices/en_GB/alan/medium/en_GB-alan-medium.onnx",
    "configPath": "assets/tts/voices/en_GB/alan/medium/en_GB-alan-medium.onnx.json",
    "sizeBytes": 63201294,
    "license": "MIT",
    "attribution": "Rhasspy Piper / alan",
    "source": "https://huggingface.co/rhasspy/piper-voices"
  },
  {
    "id": "en_GB-alba-medium",
    "name": "Alba",
    "label": "Alba \u2014 Clear",
    "locale": "en-GB",
    "region": "UK",
    "gender": "female",
    "quality": "medium",
    "family": "alba",
    "modelPath": "assets/tts/voices/en_GB/alba/medium/en_GB-alba-medium.onnx",
    "configPath": "assets/tts/voices/en_GB/alba/medium/en_GB-alba-medium.onnx.json",
    "sizeBytes": 63201294,
    "license": "MIT",
    "attribution": "Rhasspy Piper / alba",
    "source": "https://huggingface.co/rhasspy/piper-voices"
  },
  {
    "id": "en_GB-aru-medium",
    "name": "Aru",
    "label": "Aru \u2014 Clear",
    "locale": "en-GB",
    "region": "UK",
    "gender": "female",
    "quality": "medium",
    "family": "aru",
    "modelPath": "assets/tts/voices/en_GB/aru/medium/en_GB-aru-medium.onnx",
    "configPath": "assets/tts/voices/en_GB/aru/medium/en_GB-aru-medium.onnx.json",
    "sizeBytes": 76754097,
    "license": "MIT",
    "attribution": "Rhasspy Piper / aru",
    "source": "https://huggingface.co/rhasspy/piper-voices"
  },
  {
    "id": "en_GB-cori-medium",
    "name": "Cori",
    "label": "Cori \u2014 Clear",
    "locale": "en-GB",
    "region": "UK",
    "gender": "female",
    "quality": "medium",
    "family": "cori",
    "modelPath": "assets/tts/voices/en_GB/cori/medium/en_GB-cori-medium.onnx",
    "configPath": "assets/tts/voices/en_GB/cori/medium/en_GB-cori-medium.onnx.json",
    "sizeBytes": 63531379,
    "license": "MIT",
    "attribution": "Rhasspy Piper / cori",
    "source": "https://huggingface.co/rhasspy/piper-voices"
  },
  {
    "id": "en_GB-jenny_dioco-medium",
    "name": "Jenny",
    "label": "Jenny \u2014 Clear",
    "locale": "en-GB",
    "region": "UK",
    "gender": "female",
    "quality": "medium",
    "family": "jenny_dioco",
    "modelPath": "assets/tts/voices/en_GB/jenny_dioco/medium/en_GB-jenny_dioco-medium.onnx",
    "configPath": "assets/tts/voices/en_GB/jenny_dioco/medium/en_GB-jenny_dioco-medium.onnx.json",
    "sizeBytes": 63201294,
    "license": "MIT",
    "attribution": "Rhasspy Piper / jenny_dioco",
    "source": "https://huggingface.co/rhasspy/piper-voices"
  },
  {
    "id": "en_GB-northern_english_male-medium",
    "name": "Northern English Male",
    "label": "Northern English Male \u2014 Clear",
    "locale": "en-GB",
    "region": "UK",
    "gender": "male",
    "quality": "medium",
    "family": "northern_english_male",
    "modelPath": "assets/tts/voices/en_GB/northern_english_male/medium/en_GB-northern_english_male-medium.onnx",
    "configPath": "assets/tts/voices/en_GB/northern_english_male/medium/en_GB-northern_english_male-medium.onnx.json",
    "sizeBytes": 63201294,
    "license": "MIT",
    "attribution": "Rhasspy Piper / northern_english_male",
    "source": "https://huggingface.co/rhasspy/piper-voices"
  },
  {
    "id": "en_GB-semaine-medium",
    "name": "Semaine",
    "label": "Semaine \u2014 Clear",
    "locale": "en-GB",
    "region": "UK",
    "gender": "female",
    "quality": "medium",
    "family": "semaine",
    "modelPath": "assets/tts/voices/en_GB/semaine/medium/en_GB-semaine-medium.onnx",
    "configPath": "assets/tts/voices/en_GB/semaine/medium/en_GB-semaine-medium.onnx.json",
    "sizeBytes": 76737711,
    "license": "MIT",
    "attribution": "Rhasspy Piper / semaine",
    "source": "https://huggingface.co/rhasspy/piper-voices"
  },
  {
    "id": "en_GB-southern_english_female-low",
    "name": "Southern English Female",
    "label": "Southern English Female \u2014 Soft",
    "locale": "en-GB",
    "region": "UK",
    "gender": "female",
    "quality": "low",
    "family": "southern_english_female",
    "modelPath": "assets/tts/voices/en_GB/southern_english_female/low/en_GB-southern_english_female-low.onnx",
    "configPath": "assets/tts/voices/en_GB/southern_english_female/low/en_GB-southern_english_female-low.onnx.json",
    "sizeBytes": 63104526,
    "license": "MIT",
    "attribution": "Rhasspy Piper / southern_english_female",
    "source": "https://huggingface.co/rhasspy/piper-voices"
  },
  {
    "id": "en_GB-vctk-medium",
    "name": "VCTK",
    "label": "VCTK \u2014 Clear",
    "locale": "en-GB",
    "region": "UK",
    "gender": "neutral",
    "quality": "medium",
    "family": "vctk",
    "modelPath": "assets/tts/voices/en_GB/vctk/medium/en_GB-vctk-medium.onnx",
    "configPath": "assets/tts/voices/en_GB/vctk/medium/en_GB-vctk-medium.onnx.json",
    "sizeBytes": 76952753,
    "license": "MIT",
    "attribution": "Rhasspy Piper / vctk",
    "source": "https://huggingface.co/rhasspy/piper-voices"
  }
];
  const DEFAULT_VOICE_ID = "en_GB-alba-medium";
  global.MooseTTSCatalog = {
    voices: VOICES,
    defaultId: DEFAULT_VOICE_ID,
    get(id) { return VOICES.find((v) => v.id === id) || null; },
    list() { return VOICES.slice(); },
  };
})(typeof window !== "undefined" ? window : globalThis);
