/**
 * Sort It! — content packs (add new packs here only)
 * Each item: { id, label, emoji, cat }
 * cats: array of { id, label, color }
 */
window.SORT_PACKS = [
  {
    id: "living",
    subject: "Science",
    title: "Living / Non-living",
    cats: [
      { id: "living", label: "Living", color: "#22c55e" },
      { id: "nonliving", label: "Non-living", color: "#64748b" },
    ],
    items: [
      { id: "dog", label: "dog", emoji: "🐕", cat: "living" },
      { id: "tree", label: "tree", emoji: "🌳", cat: "living" },
      { id: "fish", label: "fish", emoji: "🐟", cat: "living" },
      { id: "bird", label: "bird", emoji: "🐦", cat: "living" },
      { id: "rock", label: "rock", emoji: "🪨", cat: "nonliving" },
      { id: "car", label: "car", emoji: "🚗", cat: "nonliving" },
      { id: "ball", label: "ball", emoji: "⚽", cat: "nonliving" },
      { id: "book", label: "book", emoji: "📚", cat: "nonliving" },
    ],
  },
  {
    id: "animals-plants",
    subject: "Science",
    title: "Animals / Plants",
    cats: [
      { id: "animals", label: "Animals", color: "#a855f7" },
      { id: "plants", label: "Plants", color: "#22c55e" },
    ],
    items: [
      { id: "lion", label: "lion", emoji: "🦁", cat: "animals" },
      { id: "elephant", label: "elephant", emoji: "🐘", cat: "animals" },
      { id: "monkey", label: "monkey", emoji: "🐵", cat: "animals" },
      { id: "cat", label: "cat", emoji: "🐱", cat: "animals" },
      { id: "flower", label: "flower", emoji: "🌸", cat: "plants" },
      { id: "cactus", label: "cactus", emoji: "🌵", cat: "plants" },
      { id: "sunflower", label: "sunflower", emoji: "🌻", cat: "plants" },
      { id: "tree2", label: "tree", emoji: "🌲", cat: "plants" },
    ],
  },
  {
    id: "land-water",
    subject: "Science",
    title: "Land / Water",
    cats: [
      { id: "land", label: "Land", color: "#d97706" },
      { id: "water", label: "Water", color: "#0ea5e9" },
    ],
    items: [
      { id: "cow", label: "cow", emoji: "🐄", cat: "land" },
      { id: "lion2", label: "lion", emoji: "🦁", cat: "land" },
      { id: "snake", label: "snake", emoji: "🐍", cat: "land" },
      { id: "whale", label: "whale", emoji: "🐋", cat: "water" },
      { id: "fish2", label: "fish", emoji: "🐠", cat: "water" },
      { id: "dolphin", label: "dolphin", emoji: "🐬", cat: "water" },
      { id: "crab", label: "crab", emoji: "🦀", cat: "water" },
      { id: "horse", label: "horse", emoji: "🐴", cat: "land" },
    ],
  },
  {
    id: "2d-3d",
    subject: "Maths",
    title: "2D / 3D shapes",
    cats: [
      { id: "flat", label: "2D (flat)", color: "#3b82f6" },
      { id: "solid", label: "3D (solid)", color: "#f59e0b" },
    ],
    items: [
      { id: "circle", label: "circle", emoji: "⭕", cat: "flat" },
      { id: "square", label: "square", emoji: "🟥", cat: "flat" },
      { id: "triangle", label: "triangle", emoji: "🔺", cat: "flat" },
      { id: "star", label: "star", emoji: "⭐", cat: "flat" },
      { id: "cube", label: "cube", emoji: "🧊", cat: "solid" },
      { id: "ball3d", label: "sphere", emoji: "🌐", cat: "solid" },
      { id: "box", label: "box", emoji: "📦", cat: "solid" },
      { id: "cone", label: "cone", emoji: "🍦", cat: "solid" },
    ],
  },
  {
    id: "shapes",
    subject: "Maths",
    title: "Shape sort",
    cats: [
      { id: "round", label: "Round", color: "#f59e0b" },
      { id: "sided", label: "Sides", color: "#8b5cf6" },
      { id: "pointy", label: "Pointy", color: "#ec4899" },
    ],
    items: [
      { id: "circle2", label: "circle", emoji: "🟡", cat: "round" },
      { id: "oval", label: "oval", emoji: "🏉", cat: "round" },
      { id: "square2", label: "square", emoji: "🟦", cat: "sided" },
      { id: "rect", label: "rectangle", emoji: "🟩", cat: "sided" },
      { id: "tri2", label: "triangle", emoji: "🔺", cat: "pointy" },
      { id: "star2", label: "star", emoji: "⭐", cat: "pointy" },
    ],
  },
  {
    id: "greater-smaller",
    subject: "Maths",
    title: "Greater / Smaller",
    cats: [
      { id: "greater", label: "5 or more", color: "#22c55e" },
      { id: "smaller", label: "Less than 5", color: "#f43f5e" },
    ],
    items: [
      { id: "n2", label: "2", emoji: "2️⃣", cat: "smaller" },
      { id: "n3", label: "3", emoji: "3️⃣", cat: "smaller" },
      { id: "n4", label: "4", emoji: "4️⃣", cat: "smaller" },
      { id: "n5", label: "5", emoji: "5️⃣", cat: "greater" },
      { id: "n7", label: "7", emoji: "7️⃣", cat: "greater" },
      { id: "n9", label: "9", emoji: "9️⃣", cat: "greater" },
    ],
  },
  {
    id: "vocab-animals",
    subject: "Vocabulary",
    title: "Animals",
    cats: [
      { id: "pets", label: "Pets", color: "#f472b6" },
      { id: "farm", label: "Farm", color: "#84cc16" },
      { id: "wild", label: "Wild", color: "#f97316" },
    ],
    items: [
      { id: "dog2", label: "dog", emoji: "🐶", cat: "pets" },
      { id: "cat2", label: "cat", emoji: "🐱", cat: "pets" },
      { id: "fish3", label: "fish", emoji: "🐠", cat: "pets" },
      { id: "cow2", label: "cow", emoji: "🐮", cat: "farm" },
      { id: "pig", label: "pig", emoji: "🐷", cat: "farm" },
      { id: "chicken", label: "chicken", emoji: "🐔", cat: "farm" },
      { id: "tiger", label: "tiger", emoji: "🐯", cat: "wild" },
      { id: "zebra", label: "zebra", emoji: "🦓", cat: "wild" },
    ],
  },
  {
    id: "vocab-food",
    subject: "Vocabulary",
    title: "Food",
    cats: [
      { id: "fruit", label: "Fruit", color: "#ef4444" },
      { id: "veg", label: "Veg", color: "#22c55e" },
      { id: "treat", label: "Treats", color: "#eab308" },
    ],
    items: [
      { id: "apple", label: "apple", emoji: "🍎", cat: "fruit" },
      { id: "banana", label: "banana", emoji: "🍌", cat: "fruit" },
      { id: "grapes", label: "grapes", emoji: "🍇", cat: "fruit" },
      { id: "carrot", label: "carrot", emoji: "🥕", cat: "veg" },
      { id: "broccoli", label: "broccoli", emoji: "🥦", cat: "veg" },
      { id: "corn", label: "corn", emoji: "🌽", cat: "veg" },
      { id: "cake", label: "cake", emoji: "🍰", cat: "treat" },
      { id: "cookie", label: "cookie", emoji: "🍪", cat: "treat" },
    ],
  },
  {
    id: "vocab-transport",
    subject: "Vocabulary",
    title: "Transport",
    cats: [
      { id: "landv", label: "Land", color: "#f59e0b" },
      { id: "air", label: "Air", color: "#38bdf8" },
      { id: "sea", label: "Sea", color: "#0ea5e9" },
    ],
    items: [
      { id: "car2", label: "car", emoji: "🚗", cat: "landv" },
      { id: "bus", label: "bus", emoji: "🚌", cat: "landv" },
      { id: "bike", label: "bike", emoji: "🚲", cat: "landv" },
      { id: "plane", label: "plane", emoji: "✈️", cat: "air" },
      { id: "heli", label: "helicopter", emoji: "🚁", cat: "air" },
      { id: "boat", label: "boat", emoji: "🚤", cat: "sea" },
      { id: "ship", label: "ship", emoji: "🚢", cat: "sea" },
    ],
  },
  {
    id: "phonics-b",
    subject: "Phonics",
    title: "Beginning sound: B / S",
    cats: [
      { id: "b", label: "Starts with B", color: "#3b82f6" },
      { id: "s", label: "Starts with S", color: "#ec4899" },
    ],
    items: [
      { id: "ball2", label: "ball", emoji: "⚽", cat: "b" },
      { id: "bear", label: "bear", emoji: "🐻", cat: "b" },
      { id: "bus2", label: "bus", emoji: "🚌", cat: "b" },
      { id: "sun", label: "sun", emoji: "☀️", cat: "s" },
      { id: "sock", label: "sock", emoji: "🧦", cat: "s" },
      { id: "star3", label: "star", emoji: "🌟", cat: "s" },
    ],
  },
  {
    id: "phonics-vowel",
    subject: "Phonics",
    title: "Short A / Short O",
    cats: [
      { id: "a", label: "Short a (cat)", color: "#f43f5e" },
      { id: "o", label: "Short o (hot)", color: "#8b5cf6" },
    ],
    items: [
      { id: "cat3", label: "cat", emoji: "🐱", cat: "a" },
      { id: "hat", label: "hat", emoji: "🎩", cat: "a" },
      { id: "map", label: "map", emoji: "🗺️", cat: "a" },
      { id: "dog3", label: "dog", emoji: "🐶", cat: "o" },
      { id: "pot", label: "pot", emoji: "🍲", cat: "o" },
      { id: "fox", label: "fox", emoji: "🦊", cat: "o" },
    ],
  },
  {
    id: "phonics-digraph",
    subject: "Phonics",
    title: "SH / CH",
    cats: [
      { id: "sh", label: "SH", color: "#14b8a6" },
      { id: "ch", label: "CH", color: "#f97316" },
    ],
    items: [
      { id: "ship2", label: "ship", emoji: "🚢", cat: "sh" },
      { id: "fish4", label: "fish", emoji: "🐟", cat: "sh" },
      { id: "shoe", label: "shoe", emoji: "👟", cat: "sh" },
      { id: "chip", label: "chip", emoji: "🍟", cat: "ch" },
      { id: "chair", label: "chair", emoji: "🪑", cat: "ch" },
      { id: "cheese", label: "cheese", emoji: "🧀", cat: "ch" },
    ],
  },
  {
    id: "science-materials",
    subject: "Science",
    title: "Natural / Made by people",
    cats: [
      { id: "natural", label: "Natural", color: "#22c55e" },
      { id: "made", label: "Made by people", color: "#3b82f6" },
    ],
    items: [
      { id: "leaf2", label: "leaf", emoji: "🍃", cat: "natural" },
      { id: "shell", label: "shell", emoji: "🐚", cat: "natural" },
      { id: "stone", label: "stone", emoji: "🪨", cat: "natural" },
      { id: "water2", label: "water", emoji: "💧", cat: "natural" },
      { id: "phone", label: "phone", emoji: "📱", cat: "made" },
      { id: "shoe2", label: "shoe", emoji: "👟", cat: "made" },
      { id: "pencil2", label: "pencil", emoji: "✏️", cat: "made" },
      { id: "cup", label: "cup", emoji: "☕", cat: "made" },
    ],
  },
  {
    id: "science-day-night",
    subject: "Science",
    title: "Day / Night",
    cats: [
      { id: "day", label: "Day", color: "#fbbf24" },
      { id: "night", label: "Night", color: "#6366f1" },
    ],
    items: [
      { id: "sun2", label: "sun", emoji: "☀️", cat: "day" },
      { id: "rainbow", label: "rainbow", emoji: "🌈", cat: "day" },
      { id: "bee", label: "bee", emoji: "🐝", cat: "day" },
      { id: "sunrise", label: "sunrise", emoji: "🌅", cat: "day" },
      { id: "moon2", label: "moon", emoji: "🌙", cat: "night" },
      { id: "owl", label: "owl", emoji: "🦉", cat: "night" },
      { id: "star2", label: "star", emoji: "⭐", cat: "night" },
      { id: "bat", label: "bat", emoji: "🦇", cat: "night" },
    ],
  },
  {
    id: "science-weather",
    subject: "Science",
    title: "Hot / Cold weather",
    cats: [
      { id: "hot", label: "Hot / warm", color: "#f97316" },
      { id: "cold", label: "Cold / cool", color: "#38bdf8" },
    ],
    items: [
      { id: "sun3", label: "sun", emoji: "☀️", cat: "hot" },
      { id: "icecream", label: "ice cream", emoji: "🍦", cat: "hot" },
      { id: "swim", label: "swimming", emoji: "🏊", cat: "hot" },
      { id: "fan", label: "fan", emoji: "🪭", cat: "hot" },
      { id: "snow", label: "snow", emoji: "❄️", cat: "cold" },
      { id: "coat", label: "coat", emoji: "🧥", cat: "cold" },
      { id: "cocoa", label: "hot cocoa", emoji: "☕", cat: "cold" },
      { id: "scarf", label: "scarf", emoji: "🧣", cat: "cold" },
    ],
  },
  {
    id: "science-senses",
    subject: "Science",
    title: "See / Hear / Touch",
    cats: [
      { id: "see", label: "See", color: "#a78bfa" },
      { id: "hear", label: "Hear", color: "#34d399" },
      { id: "touch", label: "Touch", color: "#fb7185" },
    ],
    items: [
      { id: "eyes", label: "eyes", emoji: "👀", cat: "see" },
      { id: "book2", label: "book", emoji: "📖", cat: "see" },
      { id: "ears", label: "ears", emoji: "👂", cat: "hear" },
      { id: "music", label: "music", emoji: "🎵", cat: "hear" },
      { id: "hands", label: "hands", emoji: "✋", cat: "touch" },
      { id: "soft", label: "soft toy", emoji: "🧸", cat: "touch" },
    ],
  },
];
